### ISSUE TITLE
Extension creates qorusproject.json even for directories that have nothing to do with Qorus

### ISSUE THREAD

**Issue by geckon** [qoretechnologies/qorus-vscode#10]
Is this on purpose? It doesn't seem very user-friendly to me.

**Comment by pvanek** [comment]
how you can decide if it's a qorus project or not? For example if you have just a poject with wsld or ssl certs for qorus instance? And these files should be deployed too...

**Comment by pvanek** [comment]
but I agree that the prj file should not be created automatically. It always must at least ask for confirmation

**Comment by pvanek** [comment]
implemented (regarding @martin-zemek )
