### ISSUE TITLE
[BUG] groups tag in interface creation page should be array of referenced objects

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#107]
Groups tag in interface creation page should be array of referenced objects, not an array of pairs (currently I'm not even able to type anything in name and desc fileds). Should also be fixed on the backend.

**Comment by turlyalz** [comment]
also I'm not able to type anything for `define-auth-label` for services - probably some bug with array-of-pairs type

**Comment by Foxhoundn** [comment]
Fixed the frontend part (array of pairs for auth labels).
