### ISSUE TITLE
[FEATURE] Add support for creation of queues, groups, events

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#108]
Add support for creation of queues, groups, events. Objects are pretty simple they have only name and description. Needs to be implemented also on the backend.

**Comment by Foxhoundn** [comment]
After disscusion with @turlyalz this will be implemented as follows:

- `iface_kind` for all of these will be `other`
- There will be one new tab called `Other`
- There will be 3 fields - `interface-type`, `name` and `desc`
- `interface-type` is enum/select where user selects one of `Queue`, `Group` or `Event`
- @martin-zemek will create an interface based on the `interface-type`
