### ISSUE TITLE
[UX] very large + icon on some API endpoint controls

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1092]
not on all:
![Qorus-IDE-API-Manager-2022-11-07](https://user-images.githubusercontent.com/13432105/200376228-ee83b079-db1a-4d16-80e1-faad81146086.png)
but on many (ex: `issue-3834-swagger` service in the Qorus repo `develop` branch):
![image](https://user-images.githubusercontent.com/13432105/200376378-9725866a-935b-4eca-ab6a-6edf4ed74ecf.png)

**Comment by Foxhoundn** [comment]
Fixed
