### ISSUE TITLE
[BUG] manage config items modal has two buttons for adding a new config item

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#114]
add new config item and (greyed out) add new

**Comment by Foxhoundn** [comment]
That’s 2 different buttons, one is for adding new config item, and the “Add new” is for adding new config item value on global/workflow level.

**Comment by davidnich** [comment]
this is confusing - also the screen is very busy like this - maybe we should consider two dialogs - one for adding / editing / removing config items and another for handling their values

**Comment by Foxhoundn** [comment]
@davidnich editing & removing is done by simple buttons + its it's own dialog, I think it's redundant to create a new dialog just to show a "Add config item" button.

I changed the first button background to green and added a line separator.

**Comment by Foxhoundn** [comment]
Fixed
