### ISSUE TITLE
Various Issues with IDE v4

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1140]
### Urgent
- [x] save string values (default + values) in config items as a YAML string (ex: `0` or `"0"`) instead of as a string in a string (currently `"\"0\""`) - this was sometimes done in the old IDE but breaks string config items - this happens when you try to save a raw value that would be interpreted as non-string type in YAML - like for example the number `0` - to enter this you have to enclose this in double quotes and then the value results in `"\"0\""` which is an error.  What should happen ideally is that any value entered in this field should simply be stored as a string if the type is `string`

### **Features for v4.1 and beyond:**
- [ ] Flow builder background paper should have grab and move, and zoom-in/zoom-out functionality
- [ ] when opening a modal to select the connector class in a connector state in an FSM, keyboard input is ignored - to fix this, please activate the input box when the dialog is opened so users can type immediately to filter the list
- [ ] add a button to the FSM page to auto align the diagram in a simple grid - to help reformat FSMs created with the old IDE that will not be rendered properly with the new IDE

### **Cannot reproduce:**
- [ ] Version doesn't clear itself when the cross button next to the version field is clicked 
![image](https://user-images.githubusercontent.com/23454410/216591224-52967a67-f391-4b75-936e-30c5320d49e6.png)
- [x] Node is not being deleted when the delete button is pressed for a node in the workflow editor
https://user-images.githubusercontent.com/23454410/216597499-95fe56c1-ed6b-4776-8e3e-9977c3c95020.mp4 - video does not work, nevertheless deleting steps works fine

### **More info needed:**
- [ ] Required fields are always red, we can have an asterisk * symbol to identify required fields and show red borders when user tries to submit without a required field
![image](https://user-images.githubusercontent.com/23454410/216557562-cacdf74e-5c62-496e-bece-b816b77db1e3.png)
- [ ] Keys of the pill can be medium instead of bold 
![image](https://user-images.githubusercontent.com/23454410/216567650-c2bcb405-eaf0-4da8-a8ee-c259c96d981c.png)
- [ ] the `subtype` field in a data provider for mappers was never set with the old IDE - it was always present as the last element of the `path` key, meaning that all older mappers are written this way (note that even Qorus ignored this key before v6 because it was never written to) - to allow IDE v4 to open mappers using data provider types created by IDE v3, it would be great to add logic to v4 if reading a data provider config for a type and `type` = `type` and `path` has a `/request` or `/response` at the end to automatically remove this from the `path` and add it to the `subtype` key to allow older mappers to be opened and then saved correctly by IDE v4

### **high priority UX / functional:**

- [x] When extendable text area is expanded to the right the resizer becomes inaccessible and goes out of view zone 
![image](https://user-images.githubusercontent.com/23454410/216560374-1d127f66-757f-409c-9636-7f5eec9d1775.png)

- [x] New service > 2nd step AddMethod - Initial description panel is too small 
![image](https://user-images.githubusercontent.com/23454410/216602757-cc645fc4-17b2-4ad7-885f-9288a432c3ab.png)
- [x] rendering issues with small screens (ex: MacBook Air)
![image](https://user-images.githubusercontent.com/13432105/216843176-8c4c7bb6-409f-4f1d-9f67-621f0b6d2196.png)
- [x] difficult to find the source directories button for new users - also only top-level directories are shown in the list - subdiretories are not shown - to add a subdirectory you have to edit the raw json

### **other:**
- [x] make it easier to see the outline of each class connector element
![image](https://user-images.githubusercontent.com/13432105/215524216-ad86d159-dd70-42b1-b941-9b4488ceded8.png)
- [x] change `1. Add New Functions` to `1. Add New Methods` in the mapper code method page

- [x] Size of connection name can be reduced to match the heading layout
![image](https://user-images.githubusercontent.com/23454410/216567908-00b9ec41-ab19-4400-98ca-5137c85df6e8.png)
- [x] Error should appear below the input 
![image](https://user-images.githubusercontent.com/23454410/216590173-ea2ed987-f206-4c6a-9284-19b6109978b5.png)

- [x] FSM throws error sometimes when try to add a new connector to flow builder 
![image](https://user-images.githubusercontent.com/23454410/216929393-7903de30-1128-44f1-b419-3d83669b62d8.png)
- [x] Create new button in the fsm flow builder does not do anything 
![image](https://user-images.githubusercontent.com/23454410/217197042-fdd9a2cd-26b7-4777-82c4-c1a9bd3c74bb.png)

done:
- [x] improve UX for simple fields
- [x] render descriptions with markdown in hover text
- [x] consider a border around modals like the FSM state - without a modal - despite the blurring of the background - it seems a small dialog border would make it easier to see the dialog boundaries as a whole
- [x] update version to 4.0
- [x] add relnotes - mention dependency on Qorus 6 for full functionality
- [x] login page when connecting to a qorus instance requiring authentication needs updating (white text on white bg)
- [x] Config Item Editor in Classes doesn't close if you discard the changes
![image](https://user-images.githubusercontent.com/23454410/214040841-7be05a70-580c-46a2-833e-04a1e50ff6e0.png)
- [x] The delete buttons to clear the fields are not working while trying to create a new connection
![image](https://user-images.githubusercontent.com/23454410/214046635-f5b95ad0-a6bf-4b66-886d-5eb7b68c9848.png)
- [x] data provider factories are not working in FSMs
- [x] FSM arrows join the following state right of center
![image](https://user-images.githubusercontent.com/13432105/214340401-b17c31f1-0a74-440d-b732-ad0760b47fb3.png)
- [x] Replace bootstrap elements with ReQore ones or hack bootstrap colors to match our color scheme
- [x] config item totals in FSM connector states are not set when the dialog is opened
- [x] left-justify field labels in mappers for improved readability
- [x] add tooltips to environment / instance buttons (connect to Qorus, edit connection parameters, delete instance)
- [x] incorrect layout in FSM states
![image](https://user-images.githubusercontent.com/13432105/215794253-f5281439-25b3-47b8-8864-d531543894df.png)
- [x] optimize labels on FSM states - initial / isolated as an icon in the title bar with hover text

**Comment by Foxhoundn** [comment]
Cannot reproduce:

- Version doesn't clear itself when the cross button next to the version field is clicked
