### ISSUE TITLE
[BUG] config item dialog issues

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#115]
the `can be undefined` and `strictly local` toggles are always checked no matter what value is selected

the description label is `field-label-description`

**Comment by Foxhoundn** [comment]
Label has to be changed by @martin-zemek on backend

**Comment by Foxhoundn** [comment]
Both `can-be-undefined` and `strictly-local` work just fine for me as well.

**Comment by Foxhoundn** [comment]
Fixed on frontend side as discussed on the meeting
