### ISSUE TITLE
objects with missing metadata for config items cause a deadlock

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#117]
it freezes on a service showing `Loading fields...` indefinitely - in that environment I eventually get the error 
```
Unable to find yaml file for class BB_SalesforceStreamBase
Code information cache update timed out, pending: getting information from qorus object parser
```

and `BB_SalesforceStreamBase` does not yet have yaml items - this is probably the reason for the freeze - however it shouldn't freeze but just display an error

**Comment by martin-zemek** [comment]
Those 2 messages are completely independent.
That there is no yaml file for BB_SalesforceStreamBase is only an information and it does not have to do with the timeout or with frontend waiting for response from backend (with Loading fields...) forever.

One error causing 'getting information from qorus object parser' staying unfinished has already been discovered and fixed, so maybe this issue will no longer occur.
