### ISSUE TITLE
[BUG] sometimes groups are not rendered correctly - see the attached screenshot

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#119]
see the `undefined` group below 

![Screen Shot 2019-10-12 at 3 52 26 PM](https://user-images.githubusercontent.com/13432105/66702493-95c8d900-ed08-11e9-964f-569cce0475b8.png)

also duplicating all the config items is confusing and hard to use with many config items as in the attached screenshot

**Comment by Foxhoundn** [comment]
1. If the group is undefined, that means it was not sent from backend (since its not mandatory)

2. What do you mean duplicating?

**Comment by davidnich** [comment]
> What do you mean duplicating?

I mean with the `Global Config Items values` (which should be `Global Config Item Values` - capitalization + extra `s`) and `Workflow Config Items values` (which should be `Workflow Config Item Values`).

I believe we can find a better way to set the value - for example maybe by listing the items only once and allowing the user to set the level manually - if we want the user to be able to set both global and local values then we could implement a dialog with both, but it seems to me that it should be either/or - the user will need to set either a local value or a global value but not both.  If you and @martin-zemek and @turlyalz have discussed this already, I would like to hear your thoughts.

**Comment by Foxhoundn** [comment]
Fixed on frontend side

**Comment by Foxhoundn** [comment]
Fixed.
