### ISSUE TITLE
[BUG] the config group field needs to be shown by default and should be required and empty

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#121]
basically config items should never have group `Default` in a real building block; we need to force the user to enter a group 

however it would be fine to use the last group value used as the default value of this field which would likely be a real timesaver when entering many config items

**Comment by Foxhoundn** [comment]
Thats a backend issue, reassigning to Martin

**Comment by Foxhoundn** [comment]
This seems to be fixed.
