### ISSUE TITLE
[BUG] IDE cannot handle more than one value map

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1225]
how to reproduce: create 2 value maps - the IDE shows the second only as a draft - if you delete the draft, it will only show the first value map - you can never open the second value map, as it does not show up in the hierarchy view

**Comment by Foxhoundn** [comment]
![CleanShot 2023-10-23 at 09 10 36](https://github.com/qoretechnologies/qorus-vscode/assets/8861481/5907f708-6c40-48bd-921e-12f7e8c08462)

Works fine for me, I will need more info on how to exactly reproduce. I just created 2 value maps, one right after the other and the IDE shows them just fine
