### ISSUE TITLE
[BUG] IDE reorders type keys when a type key is edited

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1227]
ex: if you edit a type key in a hash to set the "allow undefined values", then that key is moved to the end of the hash

This causes problems when the order must be maintained, such as when used in a mapper - for example when the output of the mapper is used to create a CSV file, and the order of the keys corresponds to the order of the fields in the file.

Ideally the order should be preserved when editing keys.

Also it would be great if the user could manually reorder keys in a hash

**Comment by Foxhoundn** [comment]
OK - shall we introduce a `sort` key on the hash then? No other way to maintain a random sort...

**Comment by davidnich** [comment]
> OK - shall we introduce a sort key on the hash then? No other way to maintain a random sort...

no problem
