### ISSUE TITLE
[BUG] Annoying notification shown after every SC action

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#123]
Notification with the following message appears after any source control system change, for example adding file to a commit. This is super annoying. It would be good if this notification was shown only once or something like that.

> Directory src in project configuration does not exist

**Comment by martin-zemek** [comment]
Your project directory does not have a 'src' subdirectory but your project configuration says that 'src' si one of the source subdirectories. So, nothing will work correctly in your project until you fix it. The message will remind you of this which is a correct behaviour.

**Comment by davidnich** [comment]
@martin-zemek if the IDE is completely broken due to this (nothing will work), then I would say that this is a bug - this can happen, and the IDE should not be totally broken

**Comment by omusil24** [comment]
IMO, there should be at least option to click in the notification like "Ignore error" or "Don't show". And then it should obviously show again whenever I try to actually do something with the Qorus extension. But it shouldn't pop-up when I'm doing unrelated actions.

**Comment by omusil24** [comment]
This does not happen anymore.
