### ISSUE TITLE
[BUG] not able to add new instance to environment on IDE home page

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#126]
the elements in the new environment (on the right) seem to be frozen - I cannot push the green button and save the new instance
<img width="1626" alt="Screen Shot 2019-10-14 at 10 53 39 PM" src="https://user-images.githubusercontent.com/13432105/66782281-a2e6f300-eed5-11e9-85e3-c4014361c1c5.png">

**Comment by Foxhoundn** [comment]
Fixed.
