### ISSUE TITLE
change Qorus link behavior in the extension

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#13]
when clicking on the link to the Qorus URL, the editor opens a browser window with the Qorus UI.

This is confusing for new users; ideally when clicking on such a link, the extension would do the following:
* if the extension can connect and can log in: show some system information and a link in the page that will allow the user to open a browser window with some explanatory text (i.e. `click the following link to open a browser windows to the Qorus web UI: https://xxxxxx`). 
* if the extension can connect but a login is required: show the login window and then after the page above
* If the extension cannot connect: then ideally the editor would show some help text and allow the user to edit the configuration

In fact if we had this functionality, then we would not need two confusing entries & it would make it much easier to connect - also maybe this way the extension could come with some default configuration - so if and when it would not work, the process of getting the user  connected to the right server would be immediately intuitive - clicking on the server info would result in helpful information and the possibility to enter in the correct URL

**Comment by pvanek** [comment]
my idea:

- instance name
  - login  (exact text. Maybe 'set as current instance'?)
  - open UI (exact text)
  - custom urls and rest of items... (not an exact text)

**Comment by davidnich** [comment]
@pvanek sounds great, go for it
