### ISSUE TITLE
[BUG] source directories pop-up with more directories 

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#130]
Before:
![Screenshot_20191016_095310](https://user-images.githubusercontent.com/11010935/66899144-c8215180-effa-11e9-8b75-42f94f25fde3.png)

After:
![Screenshot_20191016_095007](https://user-images.githubusercontent.com/11010935/66899064-a1fbb180-effa-11e9-9c29-702c55fbe27e.png)

**Comment by Foxhoundn** [comment]
Should be fixed now.
