### ISSUE TITLE
[BUG] update formatting for fixed width text to be more visible

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#135]
markdown looks cool - but see screenshot for the issue - the yellow text is really hard to read on the white
![Screen Shot 2019-10-16 at 8 12 53 PM](https://user-images.githubusercontent.com/13432105/66946585-87a0f280-f051-11e9-976e-9d2f5ab3fdfe.png)

**Comment by Foxhoundn** [comment]
Fixed.
