### ISSUE TITLE
after adding/editing a step config item workflow config items disappear

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#136]
The problem is that on adding/editing a config item the front end sends `creator-edit-interface` with `iface_kind: 'config_item'` while the logic would require `iface_kind: 'step'`.

Though it could be fixed only on backend by finding the proper `iface_kind` to the given `iface_id` (that comes in the message, too) more appropriate solution would be for the frontend to send a different message, say `update-config-item` with `iface_kind: 'step'`. Because now in the message `creator-edit-interface` `iface_id` refers to step and `iface_kind` to config item which is confusing.

**Comment by martin-zemek** [comment]
For now has been fixed on the backend.

**Comment by Foxhoundn** [comment]
Replaced the iface_kind with the real interface kind. Should be fixed now.
