### ISSUE TITLE
[BUG] IDE is redirected to login page after login is finished

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#139]
When user finishes logging in, the `close-login` event is fired which switches correctly to the Project page, but then a `return-initial-data` event fires with `tab: 'Login'` again that incorrectly opens the Login tab.

**Comment by martin-zemek** [comment]
what the issue says is not true: after login `return-initial-data` is not sent and the Project config tab is active

**Comment by Foxhoundn** [comment]
Ok, not reproducible then.
