### ISSUE TITLE
[FEATURE] sort suggestions for better user experience 

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#140]
![Screenshot_20191024_155412](https://user-images.githubusercontent.com/11010935/67492379-9fdac800-f676-11e9-8e22-ec7e4d317915.png)
![Screenshot_20191024_155558](https://user-images.githubusercontent.com/11010935/67492498-cac51c00-f676-11e9-9ef5-337aa78b32a5.png)

**Comment by Foxhoundn** [comment]
Done.
