### ISSUE TITLE
[BUG] unable to create config item with list/hash type

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#146]
unable to create config item with list/hash type - the submit button is disabled:

![Screenshot_20191025_090026](https://user-images.githubusercontent.com/11010935/67550090-f93e0800-f705-11e9-8d24-80d01c35400e.png)

![Screenshot_20191025_090151](https://user-images.githubusercontent.com/11010935/67550170-196dc700-f706-11e9-93e6-e41c85382d8d.png)

**Comment by Foxhoundn** [comment]
Fixed.
