### ISSUE TITLE
[BUG] after submitting a job warning has been shown

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#147]
After submitting a job the warning has been shown:
`Webview has been closed because current workspace has changed or has not been set`

**Comment by Foxhoundn** [comment]
Thats not really a frontend error but some internal VSCode message, I dont think there is anything we can do about that?

**Comment by turlyalz** [comment]
oh, ok

**Comment by martin-zemek** [comment]
The message is not internal, it is produced by the back-end.
And it is a correct behaviour, not a bug.
