### ISSUE TITLE
[BUG] after clicking on cancel button on login page the instance remains active

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#149]
After clicking on cancel button on login page the instance remains active.

**Comment by Foxhoundn** [comment]
Was this related to no_auth issue? I cannot reproduce this, because the instance should not be activated unless you actually submit the login.

**Comment by turlyalz** [comment]
no, it's happening now, you can test it on rippy

**Comment by Foxhoundn** [comment]
Ok, this should be fixed now.
