### ISSUE TITLE
[BUG] rendering has extra } characters in forms

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#154]
latest build from just now: https://git.qoretechnologies.com/qoretech/qorus-vscode-build/-/jobs/12604/artifacts/file/qorus-vscode-0.0.8.vsix

see screenshot:
<img width="1657" alt="Screen Shot 2019-10-31 at 12 23 25 PM" src="https://user-images.githubusercontent.com/13432105/67916549-67d50700-fbd9-11e9-8544-37b35eb5f069.png">

**Comment by davidnich** [comment]
rolling back to yesterday's build fixes the issue: https://git.qoretechnologies.com/qoretech/qorus-vscode-build/-/jobs/12583/artifacts/file/qorus-vscode-0.0.8.vsix

**Comment by Foxhoundn** [comment]
Fixed, that was a leftover character that rendered after each field.
