### ISSUE TITLE
[FEATURE] Add support for mapper-code

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#166]
Add support for functions

still TODO:
- [x] BACKEND: there is no code lens after creating mapper code
- [x] BACKEND: the Qore code created for mapper code is not subject to syntax highlighting
- [x] BACKEND: mapper code created by the IDE is shown in the hierarchy view but isn't available in the mapper `mapper codes` field
- [x] FRONTEND: the front end needs to rename `Mapper codes` to `Mapper code` in the mapper window
- [x] FRONTEND: rename `functions` to `methods` in the Edit mapper code page

**Comment by martin-zemek** [comment]
By "function" we mean both the file with functions (more precisely, pair of .yaml and .qfd files) and the individual functions in the .qfd file.

For the first meaning we could use another word, at least for the user, say "library".

When creating mappers the user will have to pick individual functions (probably in two steps: first he selects the library and then a concrete function from it). To be able to offer list of individual functions the list of functions will have to be in present also the yaml file - this will be very similar to public service methods.

**Comment by turlyalz** [comment]
this should be changed to mapper-library objects which will be used only for mappers and will have:
name, desc, author, version, code reffering to qore/java code with classes with only static functions with fixed signature (taking two auto args and returning auto).

**Comment by davidnich** [comment]
David to test

**Comment by davidnich** [comment]
mapper code is created and there is no code lens - also the Qore code is not subject to syntax highlighting

**Comment by Foxhoundn** [comment]
FE stuff is fixes.

**Comment by davidnich** [comment]
> FE stuff is fixes.

has this been pushed to `develop`?  I still see `functions` and `mapper codes` in the IDE
