### ISSUE TITLE
[FEATURE] Add support for workflow errors

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#167]
Add support for workflow errors - separate objects that can be referenced from workflows.

**Comment by davidnich** [comment]
current issues:
- [ ] missing labels in the error form
- [ ] missing label on the workflow for for errors
- [ ] missing desc in error def - required in YAML - probably a good idea to require the object to be described even if it's not loaded in Qorus
- [ ] workflow YAML file points to the object name, but oload requires the file name for loading

**Comment by martin-zemek** [comment]
As to the last point, deployment of a workflow includes the error files (among other referenced objects' files) - it has been implemented by #91
