### ISSUE TITLE
[FEATURE] Add support for editing interfaces without code

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#169]
Currently interfaces can be edited using code lenses, but in case interface has no code (e.g. value maps, groups, events, errors, workflows without code and etc.) then there is no way to edit the interface. We should provide to user some sort of list of objects on the file system (he should be able to delete and deploy interfaces and also run tests)  - simillar to what we have in `delete interface` page, but there we have only objects that are loaded to the qorus.

**Comment by martin-zemek** [comment]
The back-end part is done. On receiving the message `get-list-of-interfaces` with given `iface_kind`, returns an array of `{name, desc}` of all interfaces of given kind in the message
```
{
    action: 'return-list-of-interfaces',
    iface_kind,
    interfaces
}

```
It is supposed that the front-end will provide a table where each row has the interface name and a group of buttons for individual actions (edit, delete, deploy, test, ...?). The message for a concrete action from the front-end to the back-end will then identify the interface by name and iface_kind.
Note that interface name for steps and mappers is in the form `name:version` (but that shouldn't bother the front-end).

**Comment by turlyalz** [comment]
As agreed we are going to add file tree to the left side pane - simillar to the file system - so the same folder structure (but only folders selected in projec configuration as source directories will be shown) and there will be no yaml files. User will see interfaces and we he clicks on an interface it will open code of the interface if exists otherwise nothing. Also there will be some clickable icons for editing metadata, which will open our webview, deleting/deploying interfaces and running test files. Icons will be simillar to the icons from git lense extension for example meaning that they are visible only if user hover an interface.

**Comment by turlyalz** [comment]
The structure of tree:

Two options of ordering (should be switchable by controls in the tree (default is the second option and it should be saved to vs code settings)

1) Order by interface types:
```
│   
└─── Workflows
│    │   WORKFLOW1-1.0
│    │   WORKFLOW1-2.0
│
└─── Steps
│
└─── Services
│
└─── Jobs
│
└─── Classes
│
└─── Other
│    └─── Mappers   
│    │
│    └─── Mapper Code
│    │
│    └─── Connections
│    │
│    └─── Constants
│    │
│    └─── Queues
│    │
│    └─── Events
│    │
│    └─── Groups
│    │
│    └─── Errors
│    │
│    └─── Value-maps

```

2) Show the project structure on the FS (show only directories that are from src directories in the project configuration) - only for directories. Instead of showing files show interfaces (the same is for the first option). Don't show any other files.

Actions:
1) Deploy all interfaces (somewhere on the top of all interface types)
2) Create an interface on each interface type (if the first option is enabled) and also on each folder (if the second option is enabled)
3) Delete/deploy actions on each intefrace

**Comment by martin-zemek** [comment]
interface tree has been implemented
