### ISSUE TITLE
[BUG] Cannot manage source directories if it is an empty array

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#175]

**Comment by martin-zemek** [comment]
It the source directories array is empty **in the begining** `get-all-directories` is not called and the user has nothing to select from; moreover, "undefined" is produced as a source directory if the user clicks on the empty offer.

**Comment by Foxhoundn** [comment]
This works for me just fine, my `source_directories` in `qorusproject.json` is `[]` and I can select directories and have no `undefined` whatsoever.

**Comment by martin-zemek** [comment]
`undefined` is no longer there, I've fixed that on the frontend by ignoring such value and not sending it back to backend (and not saving to the config file).

But the problem remains: if your `source_directories` was `[]` before you opened vscode you cannot select directories because you do not have any - because you haven't called `get-all-directories`.

**Comment by martin-zemek** [comment]
Turned out to be a back-end error.
Fixed.
