### ISSUE TITLE
IDE crashes with service input

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#178]
check in the demos repo: `iot/aws-iot-demo/aws-iot-demo-1.0.qsd` (`develop` branch)

click on Edit service -> IDE crashes - no error msg is available in the extension output

**Comment by martin-zemek** [comment]
There's no yaml for this file, therefore there are no code lenses.

**Comment by martin-zemek** [comment]
The problem is due to the incorrect internal formatting of the tags of type hash (array of pairs), in this case it is `default-auth-label`. (There are three other tags of this type: workflow's `options` and `statuses` and the common tag `tags`.)

**Comment by martin-zemek** [comment]
fixed
