### ISSUE TITLE
[FEATURE] Mapper options field

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#182]
1) Please change the mapper type field to a select, on backend fetch the possible mapper types from /api/latest/mappertypes and send it in format `[{ name: ..., desc: ... }]`

2) Create new specific field Options with type `mapper_options`,  and add new flag called `required_field` with value `type`, which means this field will be disabled until the mapper type is selected. This field is a hash `{ [option]: [value based on option type] }`

**Comment by martin-zemek** [comment]
done
