### ISSUE TITLE
[BUG] fields used to generate identifiers should not be populated with or accept non-alphabetic characters

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#184]
see the attached screenshot for more info - class name `ステップの例1` will not work

![Screen Shot 2019-12-06 at 1 33 45 PM](https://user-images.githubusercontent.com/13432105/70323453-14378800-182d-11ea-9da6-4c25d9eeede8.png)

**Comment by Foxhoundn** [comment]
Can you give me a list of all fields this should be applied to?

**Comment by davidnich** [comment]
* class name
* base class name
* method names
* function names

anything that's used to derive identifiers in code - I believe the above is a complete list

**Comment by davidnich** [comment]
regex for valid identifiers: `[a-zA-Z_][a-zA-Z0-9_]*`

**Comment by martin-zemek** [comment]
in javascript it can be written this way:
