### ISSUE TITLE
[BUG] after entering a new step directly from the workflow diagram, the step is rendered as Loading step:0

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#188]
see screenshot

![Screen Shot 2019-12-06 at 1 41 32 PM](https://user-images.githubusercontent.com/13432105/70323906-64631a00-182e-11ea-838f-55e6537abe7e.png)

**Comment by Foxhoundn** [comment]
This is because of the cache timeout

![image](https://user-images.githubusercontent.com/8861481/70324453-c708e580-182f-11ea-8360-9f033f4d0d01.png)

I am sending the request for the step data

![image](https://user-images.githubusercontent.com/8861481/70324472-d38d3e00-182f-11ea-8628-d6fa036b6a11.png)

**Comment by davidnich** [comment]
cannot reproduce - looks like it's fixed

**Comment by davidnich** [comment]
this is still happening with IDE 1.2.0 develop - build from 2020-03-31 evening:
<img width="1705" alt="Screen Shot 2020-04-01 at 9 26 26 AM" src="https://user-images.githubusercontent.com/13432105/78110298-fbb23580-73fa-11ea-874c-c3c2ac02864f.png">

**Comment by davidnich** [comment]
reproduced with the latest build from develop in an new empty directory tree with the following `qorusproject.json` file:
```
{
    "qorus_instances": {},
    "source_directories": [
        "src"
    ]
}
```

as in the following screenshot - first new step in a new wf:
<img width="1495" alt="Screen Shot 2020-04-15 at 9 04 02 AM" src="https://user-images.githubusercontent.com/13432105/79308131-5322cc00-7ef8-11ea-920d-01f27271aead.png">

**Comment by davidnich** [comment]
@martin-zemek please check & verify that you can reproduce - if it's not in fact a BE bug, please reassign to Filip

**Comment by martin-zemek** [comment]
not reproducible

**Comment by davidnich** [comment]
@martin-zemek please check with Filip who can reproduce it & has more technical info about the situation
