### ISSUE TITLE
[BUG] class name field not accepting valid identifiers

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#195]
this may also be a backend bug because the names were changes on disk

see the attached screenshot - the class name was and should be the same as the object name: `BBM_AwsSnsServiceBase`

It's fine to automatically generate names in camel case, but valid class names should not be changed.

Also it's not possible to type a new valid name in this field - the string is forced to be in camel case.
![Screen Shot 2019-12-12 at 9 23 34 AM](https://user-images.githubusercontent.com/13432105/70695138-5a736800-1cc1-11ea-824c-7483bbed949a.png)

**Comment by Foxhoundn** [comment]
In this case I would suggest we do not change / generate the name at all, just let the user pick it on their own. I do not know in which case should I add camel case and not.

To fix this @martin-zemek has to stop sending me `style: camelCase` for this field.

**Comment by Foxhoundn** [comment]
I've made some choices, please try it and let me know.

**Comment by davidnich** [comment]
works exactly like I would expect - thank you!
