### ISSUE TITLE
after successful deployment there is an ID of the deployment process, is it needed?

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#20]
When a file is successfully deployed to Qorus there is a pop-up with a success message and the ID of the deployment request, is it needed for anything? Because a user asked us, that there is ID:10 but the deployed job has ID:5. They obviously have nothing in common, but, do we need to show the deployment id? Is it needed?

**Comment by martin-zemek** [comment]
There can be more than one deployments running at a time and so you can see simultaneously messages
Qorus code deployment is running (ID: 2)
Deployment finished successfully (ID: 1)

**Comment by sejvlond** [comment]
we shall just ignore it for now
