### ISSUE TITLE
implement a wizard that generates a service/job/step/workflow/mapper

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#21]
If clicking on such an item from context menu (over the files, if it's possible) it will ask you for a name and will generate a file for you, with proper extension and with a skeleton of a file (tags, name of a function based on a file name, etc...)

**Comment by pvanek** [comment]
we had quite complex wizards for such objects in previous qt-creator based ide attempt. We should follow these.

**Comment by Foxhoundn** [comment]
Outdated.
