### ISSUE TITLE
[BUG] data does not get updated after editing workflow

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#210]
1. Create workflow in the webview, select some steps, save it.
2. Click on edit button in the interface tree.
3. Add some mappers to the workflow for example, then Next and Submit. Mappers are saved to yaml file.
4. Click again on edit button in the interface tree -> mappers are missing in the webview.

Probably caused by interface tree not getting updated with new data. And therefore probably also affects other interfaces than just workflows.

**Comment by martin-zemek** [comment]
I cannot reproduce this issue. It must have been fixed along with something else.
