### ISSUE TITLE
[BUG] cannot create service with IDE if a config item is created with it

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#214]
cannot move forward from service method form; name says `Undefined` and the subtitle is `CreateMethodsTip`

only happens if a config item is created with the service - without creating any config items, everything works.

![Screen Shot 2019-12-23 at 4 28 30 PM](https://user-images.githubusercontent.com/13432105/71366144-76b8b400-25a1-11ea-8662-8837249f309a.png)

**Comment by Foxhoundn** [comment]
Cannot reproduce, creating config items does not change anything for me.

**Comment by davidnich** [comment]
I can still reproduce, but it's a complicated process:
1) create a new service and add a config item
2) add a method
3) delete the service from the hierarchy view
4) create a new service
5) add a config item - this time give it a default value
6) go to the method page., and it doesn't work anymore

not sure which of these steps is necessary, but that's how I just reproduced it from a build made a few minutes ago

**Comment by Foxhoundn** [comment]
Should be fine now.
