### ISSUE TITLE
[BUG] cannot edit other service methods

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#215]
when changing to other service methods, the IDE remains at `Loading fields...`

![Screen Shot 2019-12-23 at 4 40 18 PM](https://user-images.githubusercontent.com/13432105/71366656-f1360380-25a2-11ea-8e0e-5d38fc5e10c2.png)

**Comment by Foxhoundn** [comment]
Should be fixed, please test.
