### ISSUE TITLE
[BUG] strange state of edit form after submit

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#222]
If we edit an existing job and submit the changes the job is changed and saved properly.
But when we return to the Qorus Manager tab the original data is there, so if we submit the form again the original state will be restored. Moreover the second submit sends a create action (not an edit action) to the backend, so a message about newly created files is issued.

Other kinds of interface work differently:
- If we edit a class and return to the Qorus Manager tab after submitting the changes we have an empty form.
- If we edit a service and return to the Qorus Manager tab then on the Method page (2. step) there is the original data (same bug as with jobs) but if go Back to the 1. step the updated data is there, so if we submit it again, the main data will be ok (new) but the method original data will be restored.

**Comment by Foxhoundn** [comment]
Should be fine now.
