### ISSUE TITLE
YAML files should not be opened after creating or editing an interface

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#224]
Since it was decided that the YAML files shouldn't be manually edited by users, I believe that the YAML files should not be opened after creating or editing an interface.

Instead I think that there could be a "View Interface" page in the webview which would simply show information about the interface like it's type, name, description etc. and buttons to edit the interface, deploy it, open the code file etc. This page could also be opened when clicking on an interface in the interface tree, instead of opening the code file.

Opinions?

@turlyalz @Foxhoundn @martin-zemek @davidnich

**Comment by davidnich** [comment]
+1 sounds good to me

**Comment by Foxhoundn** [comment]
Not a fronted thing, frontend just sends an event to the backend which does all the opening.

**Comment by martin-zemek** [comment]
Yes, I agree. Now the user can see the metadata only on the edit page, so there should also be some noneditable info page.
There will not be much work on the backend, it will just send the same data as it does for the edit action. Frontend will have to create a different layout.

**Comment by martin-zemek** [comment]
> Not a fronted thing, frontend just sends an event to the backend which does all the opening. Regarding the interface info - yes, that's something I vouched for from the beginning.

Actually, the frontend sends: `"open_file_on_success": true` to the backend, thus telling backend to open the file. But it doesn't matter, we should implement the info page anyway.

**Comment by Foxhoundn** [comment]
> > Not a fronted thing, frontend just sends an event to the backend which does all the opening. Regarding the interface info - yes, that's something I vouched for from the beginning.
> 
> Actually, the frontend sends: `"open_file_on_success": true` to the backend, thus telling backend to open the file. But it doesn't matter, we should implement the info page anyway.

`open_file_on_success` is only for code files, yaml files should never be opened, no matter what the frontend sends.

**Comment by martin-zemek** [comment]
Ok, for now I will change it to let the focus stay on the webview after submit.
When we have the info page I'll change it to open that.
