### ISSUE TITLE
[FEATURE] Add generation of Java classpath and project files

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#225]
Automatically generate `.classpath` and `.project` files for correct Java support, if the files don't exist.

Make sure that Qorus java/jar files are in the classpath. Either the ones from OMQ_DIR or default ones packaged with the extension.

**Comment by turlyalz** [comment]
@omusil24, please check what we can do with java files getting compiled by the java extension in the project root

**Comment by omusil24** [comment]
@turlyalz this should be fixed now by 212f6436d8e7439f500db1f929ea47d31dccc4dd
You just need to delete the `.project` file if it already exists.
