### ISSUE TITLE
[BUG] mapper keys provided by output providers are not usable in the IDE

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#228]
ex: output provider: remote/datasources/omquser/provider/gl_record
provides mapper keys `sequence` and `sequence_currval`, but these are not available in the field

**Comment by Foxhoundn** [comment]
![Screenshot 2020-01-08 at 10 28 59](https://user-images.githubusercontent.com/8861481/71966383-b9b19300-3201-11ea-9893-f3f2076c9cb3.png)

They show for me just fine :/

**Comment by Foxhoundn** [comment]
Fixed
