### ISSUE TITLE
[BUG] if a mapper refers to an invalid mapper key, the webview crashes in the mapper page

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#230]
this could happen also if the data provider implementation changes - it should not, but the webview should not crash in that case

also an invalid data provider will cause the webview to crash - this could happen with valid data providers based on a connection that is currently down - some other more user-friendly way to handle this situation needs to be implemented

**Comment by Foxhoundn** [comment]
Fixed.
