### ISSUE TITLE
[BUG] webview crashes when I click on Manage source directories in the building-blocks repo

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#231]
repo: `https://git.qoretechnologies.com/qorus/building-blocks.git` branch: `develop`

also happens in the `demos` repo in branch `develop` - maybe everywhere?

**Comment by Foxhoundn** [comment]
@martin-zemek please switch the `get-all-directories` event to return the data in a `list`, same way we did it for the other directories calls.

**Comment by martin-zemek** [comment]
done
