### ISSUE TITLE
[BUG] cannot enter newlines in description fields in the IDE

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#232]
the only way I found to do this is to edit the text in another editor window and then paste it into the description field

**Comment by davidnich** [comment]
I only got it to work properly actually by entering the `\n` chars by hand - an actual newline did not result in a line break

**Comment by Foxhoundn** [comment]
Do you mean that it does not allow you to add new lines or there are no line breaks when you submit the description?

**Comment by davidnich** [comment]
cannot reproduce with the newest build - not sure why it didn't work with yesterday's build - closing
