### ISSUE TITLE
when the .proj file is changed, extension doesn't reload showing old qorus instances

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#24]

**Comment by martin-zemek** [comment]
You mean: When project file is changed outside VSCode.
When it is changed in VSCode the Qorus instances tree updates accordingly.

**Comment by sejvlond** [comment]
ah, okey, that's possible, we probably copied the file from other location using finder on windows... but anyway, it should be monitored if it's possible

**Comment by martin-zemek** [comment]
implemented along with #19
