### ISSUE TITLE
Webview crashes when class with no connectors is selected

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#241]
Webview crashes when class with no connectors is selected in the class-connection manager

**Comment by turlyalz** [comment]
maybe the class shouldn't be listed when adding a connector in the class-connections menu

**Comment by Foxhoundn** [comment]
@martin-zemek we will need a new call for classes, to get just a list of classes with connectors.

**Comment by martin-zemek** [comment]
let's add it to existing action `creator-get-objects` with `object_type: 'classes-with-connectors'`

**Comment by martin-zemek** [comment]
backend part done
