### ISSUE TITLE
It's not possible to open webview until code info update is completed

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#242]
It's not possible to open webview until code info update is completed. Maybe it should be somehow visible for users that code analysis is in progress otherwise they might think it's broken and not working in case code base is big (e.g. currently the demos repository takes 11 seconds).

**Comment by martin-zemek** [comment]
it's not true, you can open the webview before code info update is completed.

**Comment by turlyalz** [comment]
fixed
