### ISSUE TITLE
[BUG] Unable to set active instance after adding a directory to the src directories

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#243]
Unable to set active instance after adding a directory to the src directories in the project configuration. Clicking on the icon does nothing. It doesn't depend on the directory I'm trying to add (I tried empty directory and also a directory with some interfaces). The same is happening if I remove some of directories from the src directories.

Also if I close the webview then I'm not able to open it again until reload of the window is performed.

**Comment by turlyalz** [comment]
Update: probably the problem is with the directory I tried to add and also with empty one.

**Comment by Foxhoundn** [comment]
Seems to be working now, please reopen if you still encounter this.
