### ISSUE TITLE
[BUG] Long descriptions takes the whole screen width

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#244]
[BUG] Long descriptions takes the whole screen width - see the screenshot:

![1](https://user-images.githubusercontent.com/11010935/71986703-2f7f2400-322d-11ea-9e27-baedffcc82bb.png)

Maybe it should be trimmed.

**Comment by Foxhoundn** [comment]
This is a linux / your OS settings specific problem, because the description is a native browser `title`.
