### ISSUE TITLE
[BUG] mappers and groups are not opening

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#246]
error in IDE: `Error running command qorus.views.editMapper: Running the contributed command: 'qorus.views.editMapper' failed.. This is likely caused by the extension that contributes qorus.views.editMapper.`

This happened in yesterday afternoon's build - it was working at lunchtime - happens with every valid mapper.

**Comment by davidnich** [comment]
also happens with groups:
`Error running command qorus.views.editGroup: Running the contributed command: 'qorus.views.editGroup' failed.. This is likely caused by the extension that contributes qorus.views.editGroup.`

**Comment by martin-zemek** [comment]
I cannot reproduce it. With which concrete mapper and group does the issue happen?

**Comment by davidnich** [comment]
I also can't reproduce it - probably PBKAC!
