### ISSUE TITLE
[FEATURE] Add new event for returning specific mappers

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#250]
Add new event for returning mappers with specific conditions relative to `options`.

Both `mapper-input` and `mapper-output` have 4 keys that I will need to query - `name`, `path`, `subtype` and `type`. These keys mirror the keys in `class-connectors` `input-provider` and `output-provider` data.

I will query mappers based on the class connectors providers data for example

```
 action: 'get-mappers',
data: {
    input-condition: {
        name: 'qore:sftp-event',
        type: 'type',
    },
    output-condition: {
        name: 'mseplit',
        path: 'remote/blabla',
        subtype: 'request',
        type: 'connection',
   }
}
```

this should return all mappers that match the data exactly.

**Comment by martin-zemek** [comment]
done
