### ISSUE TITLE
[BUG] constant mapper values are shown as AutoFieldSelectType

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#256]
see screenshot - this is in the `demos` repo in mapper `gl-import` in the `develop` branch in output field `ledger_id` - the real constant value is `100`:
![Screen Shot 2020-01-12 at 8 24 05 AM](https://user-images.githubusercontent.com/13432105/72215602-2041f400-3515-11ea-91b7-70c1a427ccdc.png)

**Comment by Foxhoundn** [comment]
The auto / any field has been redesigned to properly recognise the type
