### ISSUE TITLE
[BUG] a bool config item with a default value of false cannot be saved with the default value

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#261]
the default value disappears, only `true` can be saved, and then the YAML file edited.

Also - when a default value of `true` is removed from a config item, the default value is left with value `null` and saved in the YAML

**Comment by Foxhoundn** [comment]
I fixed the handling of the boolean values, but @martin-zemek needs to fix the second part.

When you remove the `default_value` field (by clicking on trash icon) and save the config item, I send the following:

```
can_be_undefined: undefined
config_group: "Test"
description: "henlooo fren"
name: "Bool test"
orig_name: "Bool test"
type: "bool"
```

So the default_value is gone from the config item data, but the step YAML file is not altered, and new config items are not sent to the UI. That is a backend bug.

**Comment by martin-zemek** [comment]
back end part fixed

**Comment by Foxhoundn** [comment]
Fixed.
