### ISSUE TITLE
[BUG] config items of type hash accepts string default values and generate a confusing hash

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#263]
config items should only accept values that deserialize to the type and not try to force strings into a hash - for example:
![Screen Shot 2020-01-13 at 9 19 01 AM](https://user-images.githubusercontent.com/13432105/72241132-556a4700-35e6-11ea-8a87-05eaa94542fd.png)

**Comment by Foxhoundn** [comment]
The backend is parsing the yaml string I send eg `"hello: kek"` and turns it into a yaml object `hello: kek` and then sends me back `{ hello: "kek" }` in json.

The data need to remain as a string, assigned @martin-zemek.

**Comment by martin-zemek** [comment]
backend part fixed

**Comment by Foxhoundn** [comment]
Fixed.
