### ISSUE TITLE
[BUG] cannot scroll in mapper field page when dragging input fields to output fields not displayed

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#266]
if there are a lot of input and/or output fields, and the target output field for an input field is not displayed on the page, dragging the input field to the top or bottom of the page does not result in scrolling - the only way to do the mapping is to select the output field and manually set the `name` key

**Comment by Foxhoundn** [comment]
There is a magic spot on top / bottom of the output field that allows this
