### ISSUE TITLE
The Config Item Manager for workflow should not have the [Add new config item] button

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#270]

**Comment by martin-zemek** [comment]
also, the text under Workflow Config Item Values is a copy of the text for Global Config Item Values

and the header AssignNewConfig is not translated

**Comment by martin-zemek** [comment]
And also:
the button [Config items] shows (0) even in cases when there are config items. I guess that it may be because the button shows the number of **"local"** config items but in the case of workflow there are no config items, there are only workflow-level and global-level config item values.

**Comment by Foxhoundn** [comment]
Fixed.
