### ISSUE TITLE
align colors to Qore Technologies' branding

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#276]
this is cosmetic but important - the greens and reds in particular should be aligned to fit Qore Tech's colors (green with yellow = organic green etc)

**Comment by Foxhoundn** [comment]
Fixed

**Comment by davidnich** [comment]
not all greens have been updated - for example in the screenshot, the next button with mappers needs to be updated - also it seems that the green in the mappers icons in the hierarchy view should have some yellow added to it as well...

![Screen Shot 2020-02-01 at 9 11 20 AM](https://user-images.githubusercontent.com/13432105/73589176-10458080-44d3-11ea-8352-f44ae043c657.png)

**Comment by davidnich** [comment]
reopened again for the mapper field colors + mapper hierarchy icon colors which class with the qore tech green:
![Screen Shot 2020-02-05 at 5 51 01 PM](https://user-images.githubusercontent.com/13432105/73863376-3efb8800-4840-11ea-9340-be87a3f73292.png)

**Comment by Foxhoundn** [comment]
Fixed
