### ISSUE TITLE
[BUG] mapper code event is returning step classes

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#281]
Mapper code event `creator-get-objects` is returning steps

![Screenshot 2020-01-23 at 16 58 33](https://user-images.githubusercontent.com/8861481/73001381-a8bc7080-3e02-11ea-9748-9f5b6919f752.png)
![Screenshot 2020-01-23 at 16 58 41](https://user-images.githubusercontent.com/8861481/73001382-a8bc7080-3e02-11ea-9692-bc64e6f08ba3.png)

**Comment by martin-zemek** [comment]
fixed
