### ISSUE TITLE
[BUG] adding a new step to a wf causes the webview to crash

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#282]

**Comment by Foxhoundn** [comment]
Cannot reproduce, can you please write out exact steps on how to reproduce this?

**Comment by davidnich** [comment]
I'll check and close if I can't reproduce anymore either - reassigned to me

**Comment by davidnich** [comment]
is still reproducible - steps to reproduce:
1) open the `ワークフローの例` workflow and add a step to the end

the webview crashes as soon as the step is added
