### ISSUE TITLE
[BUG] expand the directory list only when choosing the source directory for the object

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#284]
or use a modal - also if a directory was already chosen, it should be used when reopening the directory control

![Screenshot_20200123_171544](https://user-images.githubusercontent.com/13432105/73002398-46646f80-3e04-11ea-939a-5c25f4b737c5.png)

**Comment by Foxhoundn** [comment]
the directories now automatically collapse after 4 seconds of not using. I have no issue with the highlighting - it works fine for me, not sure why it's not working for you, can you try again?

**Comment by Foxhoundn** [comment]
Fixed.
