### ISSUE TITLE
[BUG] clicking on the "new service" or "new job" button sometimes fails to open the new window

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#287]
when this happens I always get the following message:
`Webview has been closed because current workspace has changed or has not been set`
(also please see the screenshot below)

to reproduce, click the "New service" and "New job" buttons in succession until it fails.

This normally happens multiple times when I'm demoing the IDE.

![Screen Shot 2020-01-31 at 5 31 19 PM](https://user-images.githubusercontent.com/13432105/73556333-886a6280-444f-11ea-969f-1cccba1aa36b.png)

**Comment by martin-zemek** [comment]
fixed
