### ISSUE TITLE
[BUG] clicking Submit after editing an existing class does not open the class source

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#291]
but rather goes to an empty New class form

also in this case any changes made to the class are not saved - it seems to happen any time there are config items - even when creating a new class

**Comment by Foxhoundn** [comment]
I am correctly sending the flag, so this is something on the backend, which I noticed myself.
The created / edited interface is not updated unless vscode is reset, so I believe this is a cache issue on the backend perhaps.
When I reload vscode, everything works fine.

**Comment by martin-zemek** [comment]
not reproducible

**Comment by davidnich** [comment]
@martin-zemek as discussed - try the `building-blocks` repo and edit the `BBM_CreateOrder` class and hit `Submit` - it's taking me back to the `New class` form every time

**Comment by davidnich** [comment]
@martin-zemek this is a serious bug, because when it happens, the IDE silently discards any edits made to the metadata.  I also got an `extension host terminated` message BTW after editing the metadata and then trying to make the associated code changes

**Comment by martin-zemek** [comment]
Yes, the cause and effect go the other way: When processing and saving the edited data didn't accomplish successfully on the backend, the code file doesn't open since it is the last step.

**Comment by martin-zemek** [comment]
fixed
