### ISSUE TITLE
[BUG] inconsistent multi-line description handling

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#292]
entering a multi-line description appears fine when creating a config item, for example.

Then when viewing the description later after saving, the entire description is rendered on the same line.

Maybe there is an issue with how such strings are handled between the front and and the back end.

Additionally, with the same strings, sometimes the front end renders them with double line spacing (or > 1 in any case) and sometimes with single line spacing.  It's not clear what's causing this.

**Comment by martin-zemek** [comment]
fixed
