### ISSUE TITLE
[BUG] the "authentication not needed" warning never disappears and must be closed manually

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#305]
several minutes later:

![Screen Shot 2020-02-05 at 5 22 52 PM](https://user-images.githubusercontent.com/13432105/73860653-2a1cf580-483c-11ea-9931-4deddf35d01e.png)

**Comment by Foxhoundn** [comment]
These messages are VSCode native notifications created by backend

**Comment by omusil24** [comment]
We are doing everything right in the code. There is no setting that we could or should have set, no way to set a timeout manually or anything like that. Probably, the notification is somehow getting focus and that is causing it to not get hidden. If you click to some other part of vscode after the notification is shown, it sometimes gets hidden, albeit unreliably.

So for now, this cannot be (easily) fixed.
