### ISSUE TITLE
[BUG] Cannot read property 'type' of undefined error reported when switching to the folder view in the demos repo

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#306]
maybe only cosmetic?
![Screenshot_20200205_173652](https://user-images.githubusercontent.com/13432105/73862918-8b929380-483f-11ea-80d4-9c53fd83f277.png)

**Comment by martin-zemek** [comment]
not reproducible

**Comment by davidnich** [comment]
@martin-zemek I don't remember what this is; whatever it is, I also can't reproduce, and the screenshot doesn't really help - closing
