### ISSUE TITLE
[FEATURE] Add back working View File and Delete buttons

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#308]
![Screen Shot 2020-02-05 at 5 56 05 PM](https://user-images.githubusercontent.com/13432105/73863744-d52fae00-4840-11ea-8c2f-b9ba0793d5fc.png)

**Comment by Foxhoundn** [comment]
@martin-zemek please create 2 new events

1) first one that opens a file by the file name which I will send you.
2) second one to delete the interface and it's yaml by name and version, which I will send you as well.

**Comment by martin-zemek** [comment]
back-end part done, new messages expect the following data (can be changed):

```
{
    action: 'open-file',
    file_path: ...
}
```

```
{
    action: 'delete-interface',
    iface_kind: ...,
    name: ...
}
```
for mappers and steps `name` is in the form `name:version`, for other interfaces it's only name
