### ISSUE TITLE
[BUG] qorusproject.json cannot be edited manually or by git

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#312]
Whenever the `qorusproject.json` file is edited the IDE reverts the changes after saving the file.

**Comment by turlyalz** [comment]
is not a bug - user should not edit the config manually

**Comment by martin-zemek** [comment]
It's already closed but if someone looks at this issue later:
The title and the description are misleading: the config file can be edited manually and the changes are not reverted: the only thing that happens is that non-existing source directories are removed automatically.
