### ISSUE TITLE
[FEATURE] Check input/output types in connectors/pipelines/fsm

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#321]
Check input/output types in connectors. That means to check whether a connector can be connected to another one or if it can be triggered by a trigger and so on.

**Comment by turlyalz** [comment]
closed in favor of FSM + pipelines

**Comment by davidnich** [comment]
- [ ] pipeline elements
- [ ] FSM states
- [ ] create a REST API call to provide type compatibility info from non-identical types, args: output type/provider hash + input type/provider hash (need `PUT` request for msg body with hash) 
- [ ] pipelines require an active instance for the above call
