### ISSUE TITLE
[BUG] Mapper issues

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#325]
Issues in order of severity:
- [x] CRITICAL: the IDE will not save mappers with changes to existing custom fields, after hitting `Submit`, the IDE shows an empty `New mapper` page - to reproduce:
  - create a new mapper, select types and add a custom output field
  - save the mapper
  - reopen the mapper and delete the custom field and hit `Submit`
- [x] CRITICAL: hitting `Reset` on an existing mapper causes the webview to crash - this happens with any existing mapper (but not new mappers - that works)
- [x] CRITICAL: adding a new custom field with type `auto` and `Can be undefined` = `true` causes the webview to crash
- [x] CRITICAL: deleting a custom field with an input mapping causes the webview to crash
- [x] CRITICAL: adding a new custom field to an existing mapper with at least one mapping does not work, hitting `Submit` goes directly to an empty `New mapper` page, and the mapper is not saved
- [x] FUNCTIONAL: changing the type of a custom field works partially; the new type allows different input fields to be mapped, but reopening the field still shows the old type
- [x] FUNCTIONAL: changing a custom field's type leaves potentially incompatible input mappings in place
- [x] cosmetic: hover `AddNewMapperField` has no translation
- [x] cosmetic: modal title `AddNewField` has no translation; please note that the same label is used when editing an existing field

Also if the Qorus server is down, adding a new field results in a dialog with `Loading...` - but the modal can be closed and the webview does not crash.

**Comment by Foxhoundn** [comment]
the webview crashes when you select auto and can be null because
1. the typename is any instead of auto
2. there is no *auto in the types list

**Comment by Foxhoundn** [comment]
Fixed, please retest.
