### ISSUE TITLE
[BUG] IDE shows classes that don't support connectors in the class list

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#330]
if such a class is chosen, the webview crashes immediately - ex:
<img width="1720" alt="Screen Shot 2020-02-09 at 1 58 12 PM" src="https://user-images.githubusercontent.com/13432105/74102513-4f637980-4b44-11ea-9b87-4036ddd6c8cd.png">

maybe this is only a backend bug?

**Comment by Foxhoundn** [comment]
Fixed.
