### ISSUE TITLE
[BUG] changing a class in an interface adds the new config items to the interface without removing the old

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#331]
not sure if frontend or backend - steps to reproduce:
1) create a step
2) add a class with config items
3) change the class to another class with config items

the error is that the config items from both classes are left in the step.

The workaround is to remove the class & add a class with no config items, then save the step, and edit it again and change the class to another class - not fun.

**Comment by davidnich** [comment]
@martin-zemek to reproduce:
1) create a new step - base class `QorusNormalStep`
2) add a class with config items - ex `BBM_SalesforceStreamBase`
3) change the class to another class with config items - ex: `BBM_DataProviderSearch`

**Comment by martin-zemek** [comment]
where can I find BBM_DataProviderSearch?

**Comment by martin-zemek** [comment]
fixed
