### ISSUE TITLE
[BUG] config item cannot be type any and with a default value of null

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#337]
this is because there is no type `*any`, but in fact `any` also allows null, so this needs to be handled by the frontend somehow

![Screen Shot 2020-02-11 at 7 50 35 AM](https://user-images.githubusercontent.com/13432105/74216061-7f755e80-4ca3-11ea-8427-05d61bcf1063.png)

**Comment by Foxhoundn** [comment]
String is now always preselected type which can be set to null, which fixes the issue.
