### ISSUE TITLE
[BUG] cannot add a connector to an interface without deleting the existing connector

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#341]
I don't know if this is frontend or backend or both - steps to reproduce:
1) create an interface with a connector and save it
2) edit the interface and try to add a second connector

as soon as you try to add the second connector, the first connector disappears.

**Comment by Foxhoundn** [comment]
Not able to reproduce. Nothing disappears when editing class connections.

**Comment by davidnich** [comment]
@Foxhoundn this is still happening and is easy to reproduce - I will demonstrate in Monday's meeting

**Comment by Foxhoundn** [comment]
Fixed.
