### ISSUE TITLE
[BUG] services sometimes generated with invalid class names

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#348]
service name: `crm-account-change-event-to-order`

the class name was generated correctly in the service form

then when the code is generated, I get:
```
class crm-account-change-event-to-order inherits QorusService {
    private {
        ####### GENERATED SECTION! DON'T EDIT! ########
        ClassConnections_jSN6IDlo_uw5zhvZl class_connections;
        ############ GENERATED SECTION END ############
    }

    constructor() {
        ####### GENERATED SECTION! DON'T EDIT! ########
        class_connections = new ClassConnections_jSN6IDlo_uw5zhvZl();
        ############ GENERATED SECTION END ############
    }
}
```

I believe this was working yesterday?  not sure what's happening today, and this is not always reproducible - using my demo script I reproduced it twice this morning with the latest build from yesterday - however when making this bug report, I tried it 3 times, and it worked properly.

Also no code is generated for the `init()` method - is that correct?

Also when I try to change the class name in the service form afterwards, after fixing the generated source, the IDE does not save the changes to the YAML - it remains:
```
class-name: crm-account-change-event-to-order
```

No matter what I do ... after I hit `Submit` on the methods page, it goes directly to a blank `New service` form and does not show the service source already generated.

**Comment by martin-zemek** [comment]
Editing an interface with class connections is not yet implemented

**Comment by martin-zemek** [comment]
for services only methods created by the user are generated, if `init` is not among them than it's not

**Comment by martin-zemek** [comment]
fixed on the front end
