### ISSUE TITLE
when deployment fails show the error in the pop-up

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#35]
or at least first few hundreds chars. There may be some typos, parse-errors etc, and it's not user-friendly to go to the output of the extension to see it

**Comment by pvanek** [comment]
also please ensure that the full stdout/stderr output i shown in the console. It shows what and where is wrong.
Also we should analyze the functionality of "problems" panel. Maybe we can parse deployment output and show it there. (I'm afraid it's related to  so called "tasks" only, but maybe we can reuse it somehow)

**Comment by davidnich** [comment]
ideally the extension would open the log window if there's an error  - I think other extensions do this to show relevant info in such cases for example

**Comment by martin-zemek** [comment]
I would say that the nice system popup message window is for brief information and the log window for more detailed information (and unless the case is an error quite often there's no need to look at the log).

There was a proposal at a recent meeting that in case of error the popup window would contain a button [Show details] to open the log (if there is any more detailed info available). The other possibility is to open the log right away as suggested above.

**Comment by sejvlond** [comment]
I would go with - brief info in the pop up, if there is more, then button to "Show details"
