### ISSUE TITLE
Clarify why vscode is in dependencies list

### ISSUE THREAD

**Issue by joaomoreno** [qoretechnologies/qorus-vscode#37]
VS Code dev here. We are analyzing why extension would event get `event-stream` in their dependencies.

We noticed that `vscode` is listed in `dependencies` in your project. Is there any reason why `vscode` was moved from `devDependencies` to `dependencies`, 20 days ago?

https://github.com/qoretechnologies/qorus-vscode/commit/cb56ca0c177dcc6e3d15dae45088f19b6a174ff1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

We ask this because the recommendation is that `vscode` should be a pure `devDependency` only.

cc @egamma

**Comment by martin-zemek** [comment]
Hi João, it must have been by mistake that `vscode` was moved from `devDependencies` to `dependencies`. It will be moved back to `devDependencies` and `event-stream` will be removed in the next release. Thank you for pointing this out.
