### ISSUE TITLE
[BUG] page for deleting objects does not support scrolling

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#376]
so objects off the screen cannot be accessed:
<img width="1574" alt="Screen Shot 2020-02-21 at 10 08 08 PM" src="https://user-images.githubusercontent.com/13432105/75071920-aa0eb500-54f6-11ea-9b6b-08b323cfc594.png">

**Comment by Foxhoundn** [comment]
Fixed
