### ISSUE TITLE
[BUG] config item values not being displayed when editing config items

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#377]
not sure if it's frontend or backend

steps to reproduce:
1. open an existing object with config items or create a new object with config items
2. add a value to one of the config items and save it (hit `Submit`) 

the value is written to the yaml file but is not visible when you open the config item modal

**Comment by Foxhoundn** [comment]
This is because of #379 (frontend was sending create instead of edit and the config items got overwritten because of that).

**Comment by turlyalz** [comment]
@martin-zemek, It is not working at all in case you have inherited config items. Example given: the AwsIotDemoLookupCrmAccount step in the demos repo the `rest-supports-recovery` cfg item is inherited and shows true (which is from base class despite the fact it's overriden in the child). After changing the value it's not saved to the yaml at all.

**Comment by martin-zemek** [comment]
For me it works perfectly.

**Comment by turlyalz** [comment]
works for me also, the problem was in using old build. I will open an issue for inheriting config item default values
