### ISSUE TITLE
[FEATURE] Generate abstract metods for interfaces

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#390]
Every job must have run method - so it would be good to generate it for users (empty). Currently it's generated only in case it's used as a trigger. Also it's needed for steps:

Generate `primary` method for all step types. Generate `array` method for all array steps:
QorusEventArrayStep, QorusNormalArrayStep, QorusAsyncArrayStep, QorusSubworkflowArrayStep.

**Qore:**
* Non-array steps:
```
primary()
```

* Array steps:
```
softlist<auto> array()

primary(auto array_arg)
```

* Jobs:
```
run()
```

**Java:**
* Non-array steps:
```
public void primary() throws Throwable
```

* Array steps:
```
public Object[] array() throws Throwable
public void primary(Object array_arg) throws Throwable
```
* Job:
```
public void run() throws Throwable
```

**Comment by martin-zemek** [comment]
done
