### ISSUE TITLE
[FEATURE] Config item dialog for inherited config items 

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#394]
Currently users can override tags defined in parent config items in the inherited config items, which in case the value is the same as in the parent it will not be saved in the YAML. Or in case the user will remove the tag that is present in its parent and then close the window and open it again he will see the tag again, because it will be loaded from the parent. To address that kind of issues we need to distinguish between inherited and non-inherited tags of the config item. And users should only be able to change the value of a tag (cannot remove) or add new tags not present in its parent.

**Comment by martin-zemek** [comment]
Example:
Class `C1` defines a config item `ci` and - apart from the mandatory atrtibutes - sets also the optional attribute `default_value`.
Class `C2` inherits (or requires) `C1` and thus inherits the config item `ci`. In the edit form for `ci` there are  all the values that have been set in the class `C1`.

One thing is the weird behaviour of the optional attribute `default_value`:
- when we remove it and add it again the field is empty
- when we remove it, close the form and open the form again the field has its inherited value

I think the solution is clear: the attribute `default_value` should no longer be optional. If an optional attribute has been set in the parent it cannot be optional (removable) in the child. To implement this would be a job only for the backend.

The second question is whether we want to do something also with the mandatory attributes (maybe not):
If in the child class the values of some attributes have been changed and sometime in the future the user opens the child config item for editing he does know which values are original inherited and which are overridden.
- But does he need to know?
- Would it be of any use to have the possibility to "reset" an attribute to its inherited value?

If yes it would be work also for the frontend - optional attributes would removable by the trash button as they are now and mandatory attributes would be resetable by some other button.

**Comment by davidnich** [comment]
> I think the solution is clear: the attribute default_value should no longer be optional. If an optional attribute has been set in the parent it cannot be optional (removable) in the child. To implement this would be a job only for the backend.

very good - I agree

If in the child class the values of some attributes have been changed and sometime in the future the user opens the child config item for editing he does not know which values are original inherited and which are overridden.

> Would it be of any use to have the possibility to "reset" an attribute to its inherited value?
> If yes it would be work also for the frontend - optional attributes would removable by the trash button as they are now and mandatory attributes would be resetable by some other button.

I think it would be best to implement this - as a user I would like to know this info and have control over how to reset them back to the inherited state.

**Comment by martin-zemek** [comment]
The first part is done (config item field whose value has been set by the parent config item is mandatory in the child).
