### ISSUE TITLE
[BUG] editing a config item with a list of strings causes all characters to be separated as elements in the list

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#403]
I don't know if it's frontend or backend - 
original value: `["GET","POST","PUT","PATCH","DELETE","OPTIONS"]`
after editing it changes to: `GET,POST,PUT,PATCH,DELETE,OPTIONS`
resulting in ex:
![Screen Shot 2020-02-29 at 2 36 35 PM](https://user-images.githubusercontent.com/13432105/75608573-efd40a80-5b00-11ea-8c70-ce8f11692172.png)

**Comment by davidnich** [comment]
similar to #408

**Comment by martin-zemek** [comment]
not reproducible, works for me

**Comment by martin-zemek** [comment]
cannot reproduce
