### ISSUE TITLE
[BUG] setting the default value of a config item to a list of strings doesn't work

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#408]
each character is set as each element of the list: value = `["Content-Type", "content-type", "Content-Language", "content-language", "Accept", "Accept-Language", "Authorization"]`

result:
![Screen Shot 2020-02-29 at 7 42 47 PM](https://user-images.githubusercontent.com/13432105/75613260-c2508680-5b2b-11ea-852d-f7ccc1fe4db2.png)

**Comment by davidnich** [comment]
similar to #403

**Comment by davidnich** [comment]
editing the value manually in the yaml to look as follows seems to work:
```
    default_value:
      - "Content-Type"
      - "content-type"
      - "Content-Language"
      - "content-language"
      - "Accept"
      - "Accept-Language"
      - "Authorization"
```

**Comment by Foxhoundn** [comment]
Cannot reproduce.
I created a config item with 

```
- asg
- asga
- asgb
- asgc
- asglbb
```

and its correctly displayed in the table.

**Comment by martin-zemek** [comment]
It's correctly displayed only for the first time, when you enter the config item second time the default value is corrupted.

**Comment by martin-zemek** [comment]
fixed
