### ISSUE TITLE
[BUG] code lens showing in inappropriate/invalid location in service method

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#409]
the service has only two methods: `init()` and `getPort()`:
![Screen Shot 2020-03-01 at 9 13 14 AM](https://user-images.githubusercontent.com/13432105/75622095-00d25980-5b9d-11ea-87bd-4a5fc506cfe3.png)

**Comment by martin-zemek** [comment]
where can I find that file?

**Comment by davidnich** [comment]
@martin-zemek 
```
david@greybeard:~/src/Qorus/git/building-blocks$ git remote -v
origin	https://git.qoretechnologies.com/qorus/building-blocks.git (fetch)
origin	https://git.qoretechnologies.com/qorus/building-blocks.git (push)
david@greybeard:~/src/Qorus/git/building-blocks$ git branch
  4.0
* develop
  master
david@greybeard:~/src/Qorus/git/building-blocks$ ls -l test/service/http/rest/BBM_RestServiceBaseTest-1.0.qsd
-rw-r--r-- 1 david staff 1194 Mar  1 21:36 test/service/http/rest/BBM_RestServiceBaseTest-1.0.qsd
```

**Comment by martin-zemek** [comment]
Cannot reproduce.
When I open that particular file `building-blocks/test/service/http/rest/BBM_RestServiceBaseTest-1.0.qsd` at develop I get the method code lenses at their correct places above the init() and getPort() methods (and nowhere else).

**Comment by davidnich** [comment]
cannot reproduce - looks like it's fixed
