### ISSUE TITLE
[BUG] don't automatically hide target folders

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#417]
After a few seconds target folders are automatically hidden.

And probably we should not repeat a folder in its subfolders as you can see in the screenshot:

![image](https://user-images.githubusercontent.com/11010935/75784050-e7c6d580-5d61-11ea-92ac-6ed4314a4a7f.png)

@Foxhoundn, what do you think?

**Comment by Foxhoundn** [comment]
Done.
