### ISSUE TITLE
[BUG] value of a config item is changed when setting a config item value of type string with dashes

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#421]
Please check the `create-workflow-order-mapper` config item.

Two cases when setting `- asd - asdd` as value:

1) Setting the value for a config item of type string with dashes inside (incorrect value):
![image](https://user-images.githubusercontent.com/11010935/75895169-8ec87180-5e35-11ea-9607-b977d36057e9.png)

The value is saved as a list in the YAML:
```
value:
        ["asd - asdd"]
```

2) Setting the default value for a config item of type string (you can see there is 0 displayed):
![image](https://user-images.githubusercontent.com/11010935/75895101-75bfc080-5e35-11ea-91db-6270f1b64949.png)

The value is saved as a string in the YAML:
```
default_value:
        " - asd - asdd"
````

**Comment by martin-zemek** [comment]
it's most probably only back-end
