### ISSUE TITLE
[BUG] webview has different names in different places

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#439]
Somewhere it's "Qorus: Webview", it's title is "Qorus Manager" and maybe somewhere it's even something else. All should be the same.

**Comment by martin-zemek** [comment]
Nothing else than those two titles occur anywhere.

`Qorus: Webview` occurs only in the commands palette; the format is ok, since in the commands palette all "our" commands start with `Qorus: `.

`Qorus Manager` is the webview title, this will be changed to `Qorus Webview`.
