### ISSUE TITLE
[BUG] Manage project configuration command broken

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#440]
> command 'qorus.manageProjectConfig' not found

**Comment by turlyalz** [comment]
Do you have the qorusproject.json in your project?

**Comment by omusil24** [comment]
No need for that. The command is simply not implemented.

**Comment by martin-zemek** [comment]
The command was implemented in the past. Then handling of project configuration was implemented another way. The forgotten command can be removed.
