### ISSUE TITLE
[FEATURE] Add Edit context menu commands to files in explorer view

### ISSUE THREAD

**Issue by omusil24** [qoretechnologies/qorus-vscode#441]
Add context menu commands like "Edit Service" etc. to context menu of interface code and yaml files.

**Comment by turlyalz** [comment]
It's nice to have and ideally would be to organize those commands in sub-menus otherwise even now it takes a lot of space

**Comment by martin-zemek** [comment]
Sub-menus are not possible.

**Comment by martin-zemek** [comment]
done
