### ISSUE TITLE
[FEATURE] use static type definition as an additional input in mappers

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#445]
based on #437 

when the IDE "knows" that a mapper is being edited in the context of a workflow, such as when a connector in a step is created or edited from the wf diagram page, then the static data definition should appear under the normal type on the input side of the mapper.

When a compatible field is dragged to an output field of the mapper, the `context` key of the field mapping should be assigned a string as follows: `$static:{path.to.staticdata.key}`.

Also it would be great if we can allow the user to select the input context for the mapper (i.e. now - which wf), as we will have later data type contexts for services and jobs, and additional ones for workflows (ex: dynamic data)

**Comment by Foxhoundn** [comment]
Done.
