### ISSUE TITLE
[FEATURE] Implement context field for mappers

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#447]
Implement new `context` field for mappers. The type of this field will be `context-selector`.

This field will be a hash with 2 values: `iface_kind` and `name(:version)`

- `iface_kind` will be hardcoded on the frontend and will represent the interface
- `name(:version)` is the name of the selected interface

New event will need to be implemented, something like `get-objects-with-static-data` where frontend will send `get-objects-with-static-data: { iface_kind: 'workflow' }` and backend will need to return (`return-objects-with-static-data`) all `workflows` that have static data in format `name(:version)`. Both local and instance interfaces have to be fetched. @davidnich will create new API.

For `get-fields` for mapper we will need a new flag `context_disabled` that will indicate if the context field can be edited or not (if the user is creating the mapper from a workflow that has static data, the context cannot be edited / removed). So `mandatory` has to equal `true` as well.

### Frontend

- [x]  implement new `context-selector` field 
- [x] add `context` to `get-fields` call when creating / editing mapper from workflow
- [x] mapper input and output types/providers cannot be edited after selecting them from a connector that does not specify any types until after the mapper is reset
- [x] the `Add custom field` control is below the contextual data instead of below the type data

### Backend 

- [x] implement new `context-selector` field
- [x] implement new events `get-objects-with-static-data` and `return-objects-with-static-data` that returns selected interfaces with static data (**both local and remote**)
- [x] implement new flag for `get-fields` that disables the `context-selector` field and makes it mandatory
- [x] implement new events `get-fields-from-type` and `return-fields-from-type` - Frontend will send the value that is stored int the context `staticdata-type` field (hash with type, name, path ....) and also the built URL (`dataprovider/qore/ftp/event`). Backend has to check if this is local path = get the data from the `event.qtype` file, or ask the REST API.

### Qorus

- [x] Create new API that allows fetching of interfaces with static data

**Comment by davidnich** [comment]
@Foxhoundn the `qorus-object-parser` changes have been merged

**Comment by davidnich** [comment]
Qorus API details:
```
david@meteor:~/src/Qorus/git/qorus/Classes$ qrest system/interfacesWithDataContext -l
> GET /api/latest/system/interfacesWithDataContext HTTP/1.1
< HTTP/1.1 200 OK
< [{iface_kind: "workflow", name: "STATIC-DATA-TEST", version: "1.0", id: 228, label: "STATIC-DATA-TEST:1.0"}]
```

**Comment by Foxhoundn** [comment]
Done.
