### ISSUE TITLE
[BUG] hard crash of vscode in mapper with SOAP data provider

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#463]
to reproduce - use rippy:8092 and create a new mapper.
for the input, use `connection` -> `soap-wincash-dbod` -> `importDeliveryNoteData`

This cases the following:
<img width="1787" alt="Screen Shot 2020-03-21 at 1 55 31 PM" src="https://user-images.githubusercontent.com/13432105/77226843-a7e25980-6b7b-11ea-974a-bcf1ec45c574.png">

I can't find any error in the Qorus HTTP log file.  Also this connection is working with `qdp` and `qrest` etc

**Comment by davidnich** [comment]
depends on upstream issue: https://github.com/microsoft/vscode/issues/93370

**Comment by Foxhoundn** [comment]
![CleanShot 2023-06-08 at 09 59 27](https://github.com/qoretechnologies/qorus-vscode/assets/8861481/0f9096bd-0cb5-4e70-9b9a-e570f4cf6565)

This now works fine :)
