### ISSUE TITLE
[BUG] connector code generation must use mapAuto() instead of mapData()

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#482]
currently passing a list of data causes a type error in connector code.

- [x] revert the change of warning supression from this commit (Java) https://github.com/qoretechnologies/qorus-vscode/commit/34589c3cc9000c25289f6450becc5f054deb891e (check if needed)

- [x] Add Java import of the Hash class used below:
```
import org.qore.jni.Hash;
```
- [x] Remove the HashMap import:
```
import java.util.HashMap;
```

- [x] Use new Hash class (Java):

Before:
```
private final HashMap<String, Object> classMap;
...
classMap = new HashMap<String, Object>() {
            {
                put("BBM_CreateOrder", QoreJavaApi.newObjectSave("BBM_CreateOrder"));
            }
};
```
Should be:
```
private final Hash classMap;
...
classMap = new Hash();
classMap.put("BBM_CreateOrder", QoreJavaApi.newObjectSave("BBM_CreateOrder"));
```

- [x] Change service method signature generation for Java:

Currently:
```
public Object exchange(Map<String, Object> params) throws Throwable {
```
To be:
```
public Object exchange(Object params) throws Throwable {
```

- [x] Use mapAuto call instead of mapData (no conversion is needed):
Currently:
```
params = mapper.mapData((Map<String, Object>)params);
```
To be
```
params = mapper.mapAuto(params);
```
The same for qore

**Comment by turlyalz** [comment]
@davidnich, I've updated the issue description, please check it. And also it's not clear to me how it should work for java when we'll replace mapData() with mapAll(), because there is conversion needed for mapData and probably it will be needed also for mapAll:
```
params = mapper.mapData((Map<String, Object>)params);
```

**Comment by turlyalz** [comment]
> @davidnich, I've updated the issue description, please check it. And also it's not clear to me how it should work for java when we'll replace mapData() with mapAll(), because there is conversion needed for mapData and probably it will be needed also for mapAll:
> 
> ```
> params = mapper.mapData((Map<String, Object>)params);
> ```

should be fixed by https://github.com/qorelanguage/qore/issues/3872

**Comment by davidnich** [comment]
@turlyalz looks good to me
