### ISSUE TITLE
[BUG] timeout saving updated config item data

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#483]
description updated, on `Submit` I got the following error:
<img width="1648" alt="Screen Shot 2020-03-29 at 8 40 07 AM" src="https://user-images.githubusercontent.com/13432105/77843003-09688080-7199-11ea-8705-c24adfe23fb4.png">

the full description text is:
A hash where keys describe the data, and the values describe the target location for the data.

Keys will be processed with `UserApi::expandTemplatedValue()`; ex:
```
{"$info:started": "$pstate:last_execution_date"}
```

In a job, this will store the `started` info attribute into the `last_execution_date` key of the job's persistent state data.

**Comment by martin-zemek** [comment]
fixed
