### ISSUE TITLE
repeating subdirectories in the the directory pickers

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#489]
In the directory pickers (for fields target dir, resource, text-resource, bin-resource, template) we have lately changed the display format to show only the last subdirectory rather than the whole path (relative to the project root).
But now if in the configured source directories there is, say
```
src
a/b/services
c/d/services

```
then under the 'Show folders' we'll have
```
src
services
services
```
Is it ok?

**Comment by davidnich** [comment]
is it possible for the user to see the whole path?  In case of ambiguity it would be necessary to provide the user a way to resolve it

**Comment by turlyalz** [comment]
it's not, I think in that case it should be shown the same way as it shown in the configuration page:

![image](https://user-images.githubusercontent.com/11010935/77932946-85a0b800-72ae-11ea-8093-344e308ebed7.png)

As a tree (but only folders that are in the configurations are shown)

**Comment by turlyalz** [comment]
and also it's not necessary to show subfolders `a` and `a` are both under training.
```
training
a
a
```
which is happens now
in this case:

![image](https://user-images.githubusercontent.com/11010935/77933425-15466680-72af-11ea-99b1-c640b909d043.png)

**Comment by martin-zemek** [comment]
The point is that until recently (March 4th) we did show the whole path (relative to project root). And we changed it to the current style only because it was not nice.

**Comment by martin-zemek** [comment]
fixed on the backend
