### ISSUE TITLE
[BUG] switching from a Qore text editor to the workflow diagram view using the hierarchy doesn't work

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#495]
1) the IDE must have a non `.txt` file open (Qore, autoconf, Makefile, and shell-script files tested to trigger this bug)
2) click on the diagram control in the hierarchy view for any workflow

the following error is produced: 
```
Error running command qorus.views.editWorkflowSteps: Running the contributed command: 'qorus.views.editWorkflowSteps' failed.. This is likely caused by the extension that contributes qorus.views.editWorkflowSteps.
```

**Comment by martin-zemek** [comment]
Finally, I'm able to reproduce this issue. The point is that the open file lies outside of the project. What kind of file it is doesn't matter.

**Comment by martin-zemek** [comment]
fixed
