### ISSUE TITLE
[BUG] Cannot save new object with a class name as an existing object of another type

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#497]
ex:
- create a job named `ErpOrdersToCrm` and save it
- try to create a step with the same name

it fails, whereas there should only be a conflict if the classes have the same name for objects of the same type

**Comment by martin-zemek** [comment]
Yes, it's implemented this was deliberately. I assumed that same class name cannot be used more times in a project.

**Comment by davidnich** [comment]
@martin-zemek no that's not correct, the same class name can be used in multiple objects without problems as long as the objects are of different types.

This is pretty common and should be supported.

**Comment by martin-zemek** [comment]
Ok, now this rule is implemented only for interface names: the same name cannot be used for multiple interfaces of the same type but can be used for multiple interface of different types.

So, the same should be true also for class names?

**Comment by martin-zemek** [comment]
fixed
