### ISSUE TITLE
[BUG] webview instability

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#500]
the webview is unstable after using following service pages to the code and then clicking on `Edit service` - to reproduce:
1) edit service from the hierarchy page
2) go to the method page and click Submit
3) click `Edit service` from the code lens
After this, the webview does not work properly - after 3), you get a blank service page, and then instability; for example, trying to open a step after this results in the webview crashing.

Please note that just going to service source code and clicking `Edit service` works - to reproduce the bug, you have to first go through the service and method pages and then click `Edit service`

**Comment by martin-zemek** [comment]
Happens also with other interfaces (jobs, classes). And it also does not matter whether the editing is opened from the code lens or the tree (for both steps 1. and 3.).

The backend sends messages with the same data in steps 1. and 3., so it is a frontend bug.

Note that the error does not occur if the webview is closed between steps 2. and 3.

**Comment by martin-zemek** [comment]
See also #503
