### ISSUE TITLE
[BUG] cannot save groups

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#501]
webview remains with `Saving other...` for a long period of time, no file gets saved:
<img width="2321" alt="Screen Shot 2020-04-07 at 9 44 41 AM" src="https://user-images.githubusercontent.com/13432105/78643423-8809a000-78b4-11ea-8412-f3ac5260593a.png">

**Comment by martin-zemek** [comment]
fixed
