### ISSUE TITLE
Incremental Release - when no commit is selected, OK button is clicked, it freezes

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#51]
I have a git where there is just one branch, no tag, 1 commit

I choose an incremental release, selecting no commit, clicking OK -> spinner is on, but it freezes - doing nothing

**Comment by martin-zemek** [comment]
not reproducible

**Comment by sejvlond** [comment]
how it's not reproducible? I just reporoduced it, see the screenshots:
open a release without any branches (except for master), no tags, etc
https://ctrlv.cz/bBuu
click OK - spinner is there for ever
https://ctrlv.cz/xgKG
you can even go to full release now - still spinning
https://ctrlv.cz/fPI8
even editing files and then using context menu - make release - still spinning
