### ISSUE TITLE
[BUG] opening the qorus extension in a new & empty directory generates an error

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#511]
the error is: `Cannot read property 'interfaceDataByType' of undefined` as in the screenshot below:
<img width="1495" alt="Screen Shot 2020-04-15 at 8 55 44 AM" src="https://user-images.githubusercontent.com/13432105/79307368-12768300-7ef7-11ea-9252-1e69d7784e4c.png">

**Comment by martin-zemek** [comment]
not reproducible

**Comment by davidnich** [comment]
duplicate of #512
