### ISSUE TITLE
[BUG] prompt user to create new qorusproject.json file instead of showing a warning

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#512]
the user has no idea how to create the file if it doesn't exist.

**Comment by davidnich** [comment]
creating an empty file generates a cryptic error `{}` as in the following screenshot:
<img width="1495" alt="Screen Shot 2020-04-15 at 9 00 43 AM" src="https://user-images.githubusercontent.com/13432105/79307734-a9433f80-7ef7-11ea-8fbe-3739a631c9a2.png">

**Comment by martin-zemek** [comment]
qorusproject.json is created automatically on any action

**Comment by martin-zemek** [comment]
fixed
