### ISSUE TITLE
[BUG] Qorus login fails if the URL contains a trailing /

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#515]
ex: non-working URL: `https://localhost:8011/` 
working URL: `https://localhost:8011`

with the forward slash, the IDE shows the following error:
<img width="1873" alt="Screen Shot 2020-04-20 at 3 13 18 PM" src="https://user-images.githubusercontent.com/13432105/79755484-7e068900-8319-11ea-8061-a2e8cde9e2ce.png">

Also reported by Qorus user Vignesh here:
https://11647398089780914968.googlegroups.com/attach/1ff5fffd393ba/Screenshot%202020-04-20%20at%204.27.05%20PM.png?part=0.1&view=1&vt=ANaJVrGUiJ1oi9G2BtBDDOE9W_bAyaocvxcNUTjKCzCFADd7wUUYEaPZCMyyomZplgTJAzIWIGySkIf-WtB-JrKn4zxspNuj4sdQRi6LNSa6Yu9nA0Jxr5g

**Comment by martin-zemek** [comment]
fixed
