### ISSUE TITLE
[BUG] renaming a service method used as trigger in a class connection produces a bad result

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#516]
Note, that this is a `create new service` action, not an `edit exiting service` action:

When creating a new service, after adding a method create a class connection that uses the method as a trigger. After submitting the connection rename the method and then submit the whole service.

What should be the correct behavior?
Either: the backend refuses to save it
Or: the frontend renames the trigger automatically on renaming the method
(The backend cannot do the renaming automatically since if there are more then one methods the backend cannot know which trigger corresponds to which method.)

**Comment by turlyalz** [comment]
I think frontend should rename it automatically and in the ideal case users must be somehow informed about it when renaming a method that is used in class-connections

**Comment by Foxhoundn** [comment]
@turlyalz I guess that makes the most sense, we've talked about it some time ago but do not remember what the final verdict was
