### ISSUE TITLE
[FEATURE] Pipelines

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#546]
Add support for defining pipelines in the IDE:

Pipeline schema can be found here: https://git.qoretechnologies.com/qorus/qorus-object-parser/blob/feature/3485-fsm-pipelines/Qyaml/validation/pipeline_schema.yaml

According to the schema above the pipeline definition is simple:
it has a name and elements, where each element can be a mapper, processor or queue.

1) mapper is clear
2) processor is a special kind of class (#545)
3) queue has a name under the queue tag and must have elements (mapper/processor/queue)

The idea is to implement it in some graphical way like diagrams. + add support for type checking as we have for class-connections. (each processor can have input/output types).

Pipelines have no code (defined in YAML only).

Optional Pipeline Input Provider Support
---
To add support for an input data provider for the pipeline, the following parameters have been added to the YAML:
- `input-provider`: a hash equivalent to the `mapper-input` option but without allowing types - a data provider must be selected, not a type
- `input-provider-options`: a hash with options supported as returned from the Qorus REST API call `GET /api/latest/system/pipeline_options` - returned in the same format as mapper options (`GET /api/latest/mappertypes/Mapper/user_options`)

Pipeline Elements
---
- [x] Once a pipeline queue has another queue added to it, only additional queues can be added to the end.  It's not legal for a pipeline queue to have a processor or a mapper following a queue
- [x] Pipeline elements are run in series - each processor or mapper takes the input data and processes it and passes output to the next element in the queue for processing.  The diagram needs to reflect this - currently it's rendered as a hierarchy, and instead it should reflect the linear nature of the pipeline

**Comment by turlyalz** [comment]
```                 start
                      |
[queue1] --------- [queue2]-----------------processor3
   |                  |
   |              processor1
   |
   |
[queue3]------------[queue4]
   |                   |
   |                   |
   |                   |
processor2            mapper1
```

**Comment by davidnich** [comment]
@Foxhoundn issues:
- [ ] no pipeline entry in the hierarchy view
- [ ] I do not see any way to add elements to a pipeline:
<img width="1856" alt="Screen Shot 2020-08-03 at 8 32 47 AM" src="https://user-images.githubusercontent.com/13432105/89152731-fa894480-d563-11ea-82dc-5c76ea0fa887.png">

**Comment by davidnich** [comment]
- [ ] add hover controls to pipeline elements like with FSM states
