### ISSUE TITLE
[BUG] value map info added incorrectly to YAML

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#549]
a valid YAML-based value map (created by hand) selected in the IDE is written as follows to the YAML:
```
vmaps:
  - undefined
```

An example valid YAML value map can be found in the `demos` repo in the `develop` branch under: `/demo-scripts/erp-orders-to-crm/erp-crm-item-map.qvmap.yaml`

editing an existing step and readding the value map works.  The error only happens when added when creating a new object.

**Comment by martin-zemek** [comment]
It works for me - I edited a service and added your value map and saved and it's there in the yaml file.

(We don't support creating value maps yet though.)
