### ISSUE TITLE
[BUG] Save yaml file location to `yaml_2_name` before sending response to frontend

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#563]
Save yaml file location to `yaml_2_name` before sending response to frontend, this should be done by not sending response to the frontend before `waitForPending['yaml']` resolves.

**Comment by martin-zemek** [comment]
We don't want/need to have the yaml info updated before sending response to the frontend. We need to have the info updated when the backend starts to process possible next message from the frontend (if the info is needed for that process).

**Comment by martin-zemek** [comment]
done
