### ISSUE TITLE
[BUG] Classes - inheritance fixes

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#575]
1) Dissallow to inherit from the same class when editing a class (the `base class name` tag)
2) Base class name tag is not showing all possible classes:
   * Create a class
   * Create another class inheriting from the first one
Now if you will try to create another class inheriting from the second one the second class is not in the list. It was reproduced in the processors branch, but the bug according to @Foxhoundn is not related to that.

**Comment by martin-zemek** [comment]
It worked after reopening of vscode but not immediately. Now it's fixed.

**Comment by martin-zemek** [comment]
As to 1.: A class should be disallowed to inherit not only itself but also its descendants.

**Comment by martin-zemek** [comment]
fixed
