### ISSUE TITLE
very slow performance with Qore editing with VS Code 1.45+

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#579]
in a large project with a lot of symbols, editing Qore files is extremely slow with > 20 second delays in text entry.

Opening the same file in a VS Code editor outside the large project results in fast editing again.

Downgrading to VS Code < 1.45 also results in fast editing.

To reproduce - open VS Code 1.45.+ in the Qorus source project and edit oload for example

**Comment by omusil24** [comment]
I cannot reproduce with VSCode 1.45.1. What versions of Qore and Qorus extensions are you using? What version of Qore is used? Is it on Mac or Linux? Can you reproduce it on other machines?

**Comment by davidnich** [comment]
@omusil24 I installed the latest build of the qorus extension, and the problem has disappeared
