### ISSUE TITLE
[BUG] the webview shows a blank screen when the IDE is started without a folder being open

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#588]
We need to prompt the user to open a folder first, otherwise it looks like the webview is broken

this leads to a very confusing situation for users as in the attached screenshot:
![unnamed](https://user-images.githubusercontent.com/13432105/86230694-b59f7600-bb91-11ea-8830-068619db936f.png)

without prompting, it looks like the IDE simply does not work

**Comment by martin-zemek** [comment]
It's been fixed by preventing the webview from opening (now it does not open and immediately close)
and changing the error message from
  "Webview has been closed because current workspace folder has not been set"
to
  "Webview cannot be opened since there's no open workspace folder"
