### ISSUE TITLE
Clear the base class name select box value if it's not valid after the language change

### ISSUE THREAD

**Issue by martin-zemek** [qoretechnologies/qorus-vscode#589]
The contents of the base class name select box depends on the language, so if the user changes the language when the base class has already been selected, the selected base class may no longer be valid.

Also when the base class list is first shown to the user, it is not filtered for source language

**Comment by Foxhoundn** [comment]
Added a new event on FE `creator-change-field-value` that accepts `field` and `value` and backend can use it to change any field to any value.
