### ISSUE TITLE
[BUG] adding the same tag multiple times results in invalid YAML and an invalid interface

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#591]
ex: add the following tag twice with two different values:
`module-path`: `/Users/david/src/qore/git/module-python/test`
`module-path`: `/tmp`

the result in the YAML is:
```
tags:
    module-path: /Users/david/src/qore/git/module-python/test
    module-path: /tmp
```

The Qore YAML parser ignores the duplicate key, but it appears that the VS Code IDE's YAML parser crashes with this input.

in case of a duplicate key here, please concatenate the values with a comma (`,`):
```
tags:
  module-path: /Users/david/src/qore/git/module-python/test,/tmp
```

**Comment by Foxhoundn** [comment]
Fixed  by not allowing multiple tags with the same key

**Comment by davidnich** [comment]
fixed
