### ISSUE TITLE
[BUG] Cannot save config item with type hash, nullable, and default value = null

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#595]
<img width="1577" alt="Screen Shot 2020-07-19 at 5 13 12 PM" src="https://user-images.githubusercontent.com/13432105/87878280-8be4ac80-c9e3-11ea-89e7-b10bbd2436a6.png">

**Comment by Foxhoundn** [comment]
Should be fixed now.

**Comment by davidnich** [comment]
fixed
