### ISSUE TITLE
[BUG] IDE appears to go into a kind of infinite loop

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#602]
in the qorus repo the IDE sometimes appears to go into an infinite loop.

the hierarchy view controls do not appear to work, and the only way to reset it is to reload the webview

I'm guessing this is a backend issue, possibly related to the object parser or other filesystem scans?

I'm not yet sure how to reproduce this, but it's happened to my several times with recent builds.  It also may be related to new YAML objects where the IDE has not yet caught up to qorus + the object parser.

In any case though, confusing YAML should not cause the IDE to behave in this way.

**Comment by martin-zemek** [comment]
Which directories are supposed to be in the "source directories" configuration?

**Comment by davidnich** [comment]
@martin-zemek I have only `test`:
```
    "source_directories": [
        "test"
    ]
```

**Comment by davidnich** [comment]
@martin-zemek to reproduce - open the IDE in the qorus repo in the `develop` branch; cd to the cmake build dir and type `make docs`

After a minute or so, the IDE goes into a long (infinite?) loop and is not usable

**Comment by martin-zemek** [comment]
The heavy traffic in the cmake build directory paralyses vscode.
The directory needs to be excluded from file watching.

- open settings (File -> Preferences -> Settings)
- switch to the Workspace tab
- search for "watcher exclude"
- add a pattern there

**Comment by martin-zemek** [comment]
Info on exclusion from file watching added to README.md and issue closed
