### ISSUE TITLE
[BUG] horizontal scroll bar too narrow for mappers

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#607]
see:
<img width="1900" alt="Screen Shot 2020-08-21 at 3 33 56 PM" src="https://user-images.githubusercontent.com/13432105/90896674-59ecae80-e3c4-11ea-9e79-7a05b283ad5e.png">

**Comment by Foxhoundn** [comment]
Should work much better now.

**Comment by davidnich** [comment]
verified fixed
