### ISSUE TITLE
[BUG] missing tests

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#615]
need to write exhaustive test for each interface:
- workflows
- services
- jobs
- steps
- classes
- FSMs
- pipelines
- mappers
- mapper codes
- connections

**Comment by martin-zemek** [comment]
- [ ] create class
- [ ] edit class
- [ ] create service
- [ ] edit service
- [ ] create job
- [ ] edit job
- [ ] create workflow
- [ ] edit workflow
- [ ] create step
- [ ] edit step
- [ ] create mapper
- [ ] edit mapper
- [ ] create mapper code
- [ ] edit mapper code
- [ ] create connection
- [ ] edit connection
- [ ] create FSM
- [ ] edit FSM
- [ ] create pipeline
- [ ] edit pipeline
