### ISSUE TITLE
[BUG] provide more information directly in the main view if a deployment fails

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#649]
even if it's an indication to open the output for the extension - currently this is confusing and users don't know what to do

ex:
```
vscode -> deploy. Sometimes I get "Deployment failed" – but no additional info is shown
```

**Comment by martin-zemek** [comment]
By "main view" you mean webview or the system message window in the bottom right corner?
Do you want to put there what currently is only in the log window?

**Comment by davidnich** [comment]
> By "main view" you mean webview or the system message window in the bottom right corner?
> Do you want to put there what currently is only in the log window?

I mean whatever the IDE is displaying when a deployment is made and fails.  I would like to make it clear to the user how to get the details for the error.  We can discuss how to do that - if you have some ideas, let's discuss them.

**Comment by martin-zemek** [comment]
In the past we considered adding a button to the system message window that would open the log.
