### ISSUE TITLE
[BUG] when adding a new step, an error message is raised

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#651]
<img width="2032" alt="Screen Shot 2020-11-04 at 1 48 59 PM" src="https://user-images.githubusercontent.com/13432105/98113918-a7959500-1ea4-11eb-93b6-5bf3d4b0b895.png">

appears to be only cosmetic - all step files are in fact created - maybe there's a race condition

**Comment by martin-zemek** [comment]
Are you creating a new workflow or editing an existing one?
Are you adding an existing step or creating a new one?
Actually, I cannot reproduce the issue in any scenario.

**Comment by davidnich** [comment]
creating a new workflow, creating a new step
