### ISSUE TITLE
[BUG] removing a class used by a connection does not result in the connection being deleted

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#657]
after this, the connection remains there and cannot be deleted:
<img width="1980" alt="Screen Shot 2020-11-04 at 8 01 28 PM" src="https://user-images.githubusercontent.com/13432105/98156773-8c447d00-1ed8-11eb-9aaf-b343f30a49b8.png">

**Comment by Foxhoundn** [comment]
Fixed.
