### ISSUE TITLE
[BUG] IDE fails to add 3rd parallel step in workflow

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#658]
and adds it below instead - see the following screenshot:

I had only three steps as follows:
<img width="2322" alt="Screen Shot 2020-11-05 at 8 13 48 AM" src="https://user-images.githubusercontent.com/13432105/98209225-dceec100-1f3e-11eb-84e5-5d27686b17ec.png">

Then I clicked on the right side of the last step (`Add new step parallel to BBM_TestSftpWorkflowStep`); instead of adding the step in parallel, it was added after the step:
<img width="2366" alt="Screen Shot 2020-11-05 at 8 10 06 AM" src="https://user-images.githubusercontent.com/13432105/98208956-74074900-1f3e-11eb-940d-086300fbe9e3.png">

To create the workflow, I had to edit the yaml manually.

Please fix the following issues:
- [x] incorrect dependency issue as above
- [x] clipped hover text as in the first screenshot
- [x] add the ability for the user to resize the panes by dragging left and right in the vertical area between the hierarchy view (`1. Add Workflow Steps`) and the diagram area (`2. Workflow Step Diagram`); currently there is a horizontal scroll bar under `1`, and as the hierarchy gets more complex, more of the hierarchy boxes will be clipped

**Comment by Foxhoundn** [comment]
Fixed
