### ISSUE TITLE
[BUG] recreating a step with another language results in an error

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#666]
<img width="2366" alt="Screen Shot 2020-11-06 at 1 22 39 PM" src="https://user-images.githubusercontent.com/13432105/98365762-29b3c400-2033-11eb-94cf-21b1e76cb0e9.png">

**Comment by martin-zemek** [comment]
it's not an error, it's a correct behaviour

**Comment by martin-zemek** [comment]
Fixed
