### ISSUE TITLE
[BUG] crash in the IDE opening interfaces from the code lens

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#683]
the service is in the `demos` repo: `maxis/maxis-api-1.0.qsd`

to reproduce:
1) open the code for the service in the IDE
2) click on the `Edit service` code lens control

result:
<img width="2134" alt="Screen Shot 2020-12-03 at 10 42 45 AM" src="https://user-images.githubusercontent.com/13432105/100992566-9cda2880-3554-11eb-8254-8b2a1923d9b9.png">

opening the service from the hierarchy view works fine

**Comment by martin-zemek** [comment]
the message `Referenced group '[object Object]' not found` is also wrong:
should have been `Referenced group 'MAXIS-CRM' not found`
