### ISSUE TITLE
[BUG] service cannot be saved after changing base class and removing required class

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#700]
scenario: service created with base class with many config items
the service was then later opened and changed; the base class was removed and changed to `QorusService` and the required class was also removed, removing all config items.
In the service method page, the IDE refused to move forward with an error:
<img width="1831" alt="Screen Shot 2020-12-21 at 9 29 13 PM" src="https://user-images.githubusercontent.com/13432105/102819941-b1cc0e00-43d4-11eb-9e98-e44106ccedd4.png">

**Comment by martin-zemek** [comment]
cannot reproduce
