### ISSUE TITLE
[BUG] editing a class from an interface causes all class connections to disappear

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#752]
tested with repo `building-blocks` in branch `feature/example_chatbot` editing `examples/service/http/websockets/chatbot-ws-demo-1.0.qsd.py`
- edit one of the classes, no need to make any actual changes, click `Submit` (if you cancel, the bug does not trigger)
- when you go back to the service, all connections have disappeared

**Comment by Foxhoundn** [comment]
This is intentional
