### ISSUE TITLE
[BUG] missing scrollbars in 'delete interfaces' tab

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#85]
Missing scrollbars in 'delete interfaces' tab (workflows, services, jobs, probably everywhere):

![Screenshot_20190927_090822](https://user-images.githubusercontent.com/11010935/65749550-8b9ebc00-e106-11e9-99fe-624986bdb029.png)

**Comment by Foxhoundn** [comment]
Fixed.
