### ISSUE TITLE
after saving changes to qorus instances everything dissapears except for environments tab

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#86]
After saving changes to qorus instances everything dissapears except for environments tab.

![Screenshot_20190927_091356](https://user-images.githubusercontent.com/11010935/65749826-36af7580-e107-11e9-88f1-3823c8016742.png)

After clicking on save (or hitting enter key) it looks like:
![Screenshot_20190927_091410](https://user-images.githubusercontent.com/11010935/65749843-4464fb00-e107-11e9-873e-1cf6cec337e8.png)

**Comment by Foxhoundn** [comment]
Fixed with new project page implementation.
