### ISSUE TITLE
[BUG] service method - lock tag doesn't work properly

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#87]
I can't remove default value (`none`) of lock tag using backspace in the service method page. I'm able to remove everything except for the last `n` character. And also any string is allowed to be typed. But the documentation says: 
`must be either none, read, or write (default none), to determine how the service's RWLock will 
be grabbed before the method is executed`

So, maybe it has to be fixed also on the backend.

**Comment by Foxhoundn** [comment]
This should be an enum with the 3 possible values, reassigning to Martin.
