### ISSUE TITLE
[BUG] suggestion pop-up with a lot of objects looks weird

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#90]
see the screenshot:

![Screenshot_20191008_122622](https://user-images.githubusercontent.com/11010935/66388751-14e7a580-e9c7-11e9-9162-76ae477a956a.png)

Only part of objects should be shown and the scroolbar should be in the pop-up window, not in webview itself

**Comment by turlyalz** [comment]
also, if I type anything it's not searching at all

**Comment by Foxhoundn** [comment]
fixed
