### ISSUE TITLE
[BUG] draft is being saved in an infinite loop causing performance problems

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#909]
the IDE becomes extremely slow - > 30s to add a config item - on the console the following message is repeated many times a second:
```
[Extension Host] SAVING DRAFT WITH THIS DATA class cb0dc00a62c72baf7d880ef50778e16f {fields: Array(12), selectedFields: Array(9), isValid: true, interfaceId: "cb0dc00a62c72baf7d880ef50778e16f", associatedInterface: "/home/david/src/Qorus/git/building-blocks/generic/BBM_SmtpEmailSender-1.0.qclass", …}
```
![image](https://user-images.githubusercontent.com/13432105/148414224-d22863cf-6f79-464a-8ecc-427369e363cf.png)

**Comment by Foxhoundn** [comment]
How exactly do I reproduce this? I've been playing with config items for ~30 mins right now on one interface and I didn't encounter the infinite loop
