### ISSUE TITLE
[FEATURE] deploying an interface with all dependencies

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#91]
Currently to deploy an interface you need to include all dependencies as classes, functions, mappers, groups etc. in the deploy set. It would be good if it's done by the IDE, so user will just deploy an interface and all deps will be resolved for him.

**Comment by davidnich** [comment]
@martin-zemek this works well - I was wondering if we should maybe include a button in the confirmation request that would allow the user to only deploy the single object without dependencies if the user wants to - there could likely be some reason to do this - let me know what you think

**Comment by martin-zemek** [comment]
Yes, it can be done by partly returning previous implementation that in the deployment included only the pair file (source for given yaml or yaml for given source) and service resources.
