### ISSUE TITLE
[BUG] webview is shown correctly only if it's open from context menu

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#92]
Only by going from context menu (right click on the folder in the left sidebar) opens the webview with icons. If I try to open the webview using qorus button in the top right corner or if I switch between tabs in the webview it opens without any icons (java, qore and qorus icon in the top left corner), and also step diagram looks differently if I switch the tab, see the screenshot:

Before:

![Screenshot_20191008_130248](https://user-images.githubusercontent.com/11010935/66390924-03ed6300-e9cc-11e9-93c5-ac0029e5ba5d.png)

After:

![Screenshot_20191008_130219](https://user-images.githubusercontent.com/11010935/66390921-02239f80-e9cc-11e9-8c98-c044177095f6.png)

**Comment by Foxhoundn** [comment]
That’s not a frontend issue (because it works at least one way), thats backend not sending path correctly issue I believe.

**Comment by Foxhoundn** [comment]
Fixed.
