### ISSUE TITLE
[BUG] Improve items order in a context menu

### ISSUE THREAD

**Issue by shev-vadim-net** [qoretechnologies/qorus-vscode#959]
Hello. Thank you for this cool plug-in.

I faced a small issue. When I select a single Step and call a context menu I see the items in order:
- Deploy file to active Qorus instance
- Edit
![Screenshot with a single selected item](https://user-images.githubusercontent.com/772061/158800473-f45d65e8-ab06-434e-a0aa-5e770c174e57.png)

But when I select multiple Steps and call the same menu the order is different:
- Edit
- Deploy Selected Files and Directories
![Screenshot with multiple selected items](https://user-images.githubusercontent.com/772061/158801301-c0fb6f83-4bc4-4762-9b5a-ffd523c527e8.png)

Would be great to have the same order of items, because it's easy to miss-click.

**Comment by Foxhoundn** [comment]
Fixed in 3.3.0
