### ISSUE TITLE
Unexpected behaviour when adding a new Allowed value in the Config item editor

### ISSUE THREAD

**Issue by shev-vadim-net** [qoretechnologies/qorus-vscode#966]
Hello. I have an issue when I edit the Config items of an existing Class in the Config item editor.
![Снимок экрана 2022-03-24 в 20 24 43](https://user-images.githubusercontent.com/772061/159926841-3cae3e27-0cdb-41a0-8800-54bfcc49ee92.png)
When I click on `+` it cleans the second item instead of adding the forth. If I click again it cleans the third item. And only after clicking again it adds the forth blank item.
![Снимок экрана 2022-03-24 в 20 25 05](https://user-images.githubusercontent.com/772061/159927408-30a25b64-c88f-48f9-a489-78ca6203fcaa.png)

**Comment by Foxhoundn** [comment]
Fixed in 3.3.0
