### ISSUE TITLE
Qorus instance is not being sent in initial data

### ISSUE THREAD

**Issue by Foxhoundn** [qoretechnologies/qorus-vscode#97]
When you set an instance as active, and then open the webview, the instance is nowhere available (unless doing other calls). Please send the `qorus_instance` in initial data when opening web view.

**Comment by martin-zemek** [comment]
Yes, I'll add qorus instance to the initial data for the case that it has already been set when the webview opens, but remember that there is also the message `current-qorus-instance` that the backend sends whenever active qorus instance changes (or is unset).

**Comment by martin-zemek** [comment]
Backend part done: I've added `qorus_instance` to the initial data message but since the webview still does not show it I assume that something needs to be done on the frontend as well.

**Comment by Foxhoundn** [comment]
Done.
