### ISSUE TITLE
[BUG] WebView crash with the API call state in FSMs 

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#988]
to reproduce:
* add an API call state to an FSM with the following data provider factory: `connection` -> `rest-billing-demo` -> `accounts` -> `GET`
* enable `Allow API Arguments`

at this point the webview crashes with a white screen.

![image](https://user-images.githubusercontent.com/13432105/164499205-33abea5c-9ed8-41aa-88a1-b16d2ebee8fc.png)

**Comment by Foxhoundn** [comment]
The call is:

https://hq.qoretechnologies.com:8092/api/latest/remote/user/rest-billing-demo/provider/accounts/GET/request?context=ui 

The response is missing the `type` key

![CleanShot 2022-04-26 at 09 51 06](https://user-images.githubusercontent.com/8861481/165249989-4dc2401e-c48b-4878-bee0-e4f10194be76.png)

Example call to https://hq.qoretechnologies.com:8092/api/latest/dataprovider/factories/qorus-api/provider/util/log-message/request?context=ui which yields

![CleanShot 2022-04-26 at 09 56 25](https://user-images.githubusercontent.com/8861481/165250857-08dcd43a-85f5-4a6c-ba78-0042e27d8840.png)

So the difference is one API is returning `type`, the other is returning `base_type` it looks like - this should be unified.

**Comment by davidnich** [comment]
issue will be fixed in Qorus 5.1.32
