### ISSUE TITLE
[BUG] crash in Mappers with a table-based data provider

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#999]
if any table-based data provider is selected, the IDE will crash - ex: use `datasource -> omquser -> bb_local` as input and when you clikc the green button to confirm, the webview crashes

**Comment by Foxhoundn** [comment]
The issue happens because type is a string `"type":"DbTableDataProvider",` which it never is for other providers - it needs to be a hash with all the different type information (types_accepted, types_returned etc)

**Comment by davidnich** [comment]
API issues fixed in Qorus - was a regression in 5.1.33
